/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Join the Discord!": "加入 Discord!",
    "Fix export button and save": "修复导出按钮和保存",
    "ENABLED": "启用",
    "Export to file": "导出为文件",
    "Import clipboard": "从剪贴板导入",
    "Import file": "从文件导入",
    "DISABLED": "禁用",
    "Experience": "经验值",
    "Cancel": "取消",
    "/s": "/秒",
    "% Tile Cost": "% 方块成本",
    "About": "关于",
    "← Previous": "← 上一条",
    "by BlacKcuD": "作者 BlacKcuD",
    "An Incremental Grid-Based Strategy Game": "一款基于网格的渐进式策略游戏",
    "Did you know?": "你知道吗？",
    "Each square type generates different resources.": "每种方块类型都会产生不同的资源。",
    "Idle-Squares": "方块放置",
    "IDLE-SQUARES": "方块放置",
    "Loading sprites...": "正在加载贴图...",
    "Meadows": "草地",
    "Next →": "下一条 →",
    "Resources": "资源",
    "Skip Tutorial": "跳过教程",
    "Wisdom": "智慧",
    "Stone": "石头",
    "Wood": "木头",
    "Your goal is to conquer the entire map by purchasing all tiles. Once complete, advance to the next map and repeat.": "你的目标是通过购买所有方块来征服整个地图。完成之后，就前往下一个地图并重复此过程。",
    "Welcome to Idle-Squares!": "欢迎来到 方块放置!",
    "Upgrades": "升级",
    "Unlocking Tiles": "解锁方块",
    "Wisdom Grid Upgrades": "智慧网格升级",
    "The Grid": "网格",
    "Progress far enough and you'll unlock the Wisdom Grid—a powerful upgrade system that makes every future run stronger. Resetting to claim your Wisdom Points is a milestone, not a setback. Build your permanent power and conquer faster each time!": "继续前进到一定程度，你就能解锁“智慧网格”——这是一个强大的升级系统，能让你每次的后续游戏都变得更加强大。重新开始以获取你的“智慧点数”是一个重要的里程碑，而非挫折。积累你的永久力量，每次都能更快地取得胜利！",
    "This is your territory. You start with one unlocked tile. Expand by purchasing adjacent tiles. Tile costs increase significantly the further you expand and the more you own—strategic planning is essential.": "这是你的领地。你一开始拥有一个未锁定的方块。通过购买相邻的方块来扩大领地范围。随着扩张范围的扩大以及拥有的方块数量的增加，方块的成本也会大幅提高——因此，进行合理的规划至关重要。",
    "Crafting recipes unlock as you progress through the game.": "随着游戏进程的推进，您会解锁制作配方。",
    "Purchase adjacent tiles to expand your territory and explore the map. Each tile costs resources based on its distance from your starting tile and your current progress.": "购买相邻的方块可以扩大您的领地并探索地图。每个方块的成本取决于其与您起始方块的距离以及您当前的进展程度，其所需资源量会有所不同。",
    "Unknown Territory": "未知领土",
    "Keyboard shortcuts available - press ? in the top right to see them.": "键盘快捷键可用——在右上角按“？”键即可查看。",
    "Forest": "森林",
    "Iron Mine": "铁矿",
    "Initializing game...": "正在初始化游戏...",
    "Quarry": "采石场",
    "Tent": "帐篷",
    "Coal Deposit": "煤矿床",
    "A coal deposit that produces Coal": "产出煤炭的煤矿",
    "A dense forest that produces Wood": "一片茂密的森林，能产出木头",
    "A stone quarry that produces Stone": "可以生产石头的采石场",
    "An iron mine that produces Iron Ore": "一个铁矿，能产出铁矿石",
    "Hover over items to see more information about them.": "点击物品可查看更多相关信息。",
    "Unlock adjacent tiles first": "首先解锁相邻的方块",
    "Your humble beginnings": "你的卑微起点",
    "Achievement Unlocked!": "成就已解锁!",
    "Yay!": "耶!",
    "Nice Tutorial": "精彩的教程",
    "Play on Meadows for 10 minutes.": "在草地上玩 10 分钟。",
    "Shrine": "神殿",
    "Empty Land": "空地",
    "Coal": "煤",
    "A sacred shrine surrounded by mountains that increases all resource gains by 10%": "一座群山环绕的神殿，使所有资源收益提高10%",
    "An empty plot of land that serves no purpose, yet": "一块空旷的土地，毫无用途可言，",
    "Unlocking new squares opens up more resources to generate.": "但解锁新的区域后，会带来更多可生成的资源。",
    "Unlock Upgrades": "解锁升级",
    "An empty plot of land that serves no purpose, yet": "一块没有任何用途的空地",
    "Apprentice Tree Cultivation": "学徒树栽培",
    "Chop Chop!": "砍砍!",
    "Clever Stone Stacking": "巧妙的石头堆砌",
    "Coal Warehousing": "煤炭储存",
    "Continuous Improvements": "持续改进",
    "Diggy Diggy Hole": "挖，挖，挖",
    "Empty Land tile cost is 50% cheaper": "空地方块成本降低50%",
    "Forest tile cost is 20% cheaper and increases Wood storage by 200": "森林方块成本降低20%，木头储存量增加200",
    "Increases Coal storage by 50 per Empty Land owned": "每拥有一个空地，煤炭储存量增加 50",
    "Increases Iron Ore storage by 50 per Empty Land owned": "每拥有一个空地，铁矿石储存量增加 50",
    "Increases Stone storage by 50 per Empty Land owned": "每拥有一个空地，石头储存量增加 50",
    "Increases storage capacity of all resources by 1 every second (caps at 10,000)": "所有资源的存储容量每秒增加 1（上限为 10，000）",
    "Iron Ore Warehousing": "铁矿石储存",
    "It`s bigger on the inside": "内部更大",
    "Log Piles": "木头堆",
    "Lumber Warehousing": "木头仓库",
    "Nothing but space": "一片空旷之地",
    "Pile On": "堆积起来",
    "Protected Forests": "森林保护区",
    "Stone Warehousing": "石头仓库",
    "Weatherproof Storage Area": "防风雨储存区",
    "You can save your game at any time with Ctrl+S!": "您可以在任何时候通过按 Ctrl+S 保存游戏！",
    "But what does it do?": "但它究竟有什么作用呢？",
    "Woodstock": "木头存储",
    "Forge": "锻炉",
    "Fuel for the Fire": "生火燃料",
    "Iron Ore": "铁矿石",
    "Riverside": "河畔",
    "Dark Forest": "黑暗森林",
    "Crystal Peak": "水晶山",
    "Own a Shrine": "拥有一个神殿",
    "Own a Dark Forge.": "拥有一个黑暗锻炉.",
    "Own a Dark Forge on Riverside": "在河畔拥有一个黑暗锻炉",
    "Own your first Forge": "拥有你的第一个锻炉",
    "Buy 25 Upgrades in one run": "在单轮游戏中购买 25 升级",
    "A blazing hot forge that refines 1 Coal + 1 Iron Ore into 1 Iron Ingot every second": "一个炽热的熔炉，每秒将1个煤+ 1个铁矿石提炼成1个铁锭",
    "A majestic mountain peak - an expensive landmark with no practical benefit, yet": "一座雄伟的山峰——这是一座昂贵的地标性建筑，但毫无实际用途。",
    "Achievement Points": "成就点数",
    "All tiles become cheaper to purchase based on your total Achievement Points.": "根据您的总成就点数，所有方块的购买价格都会降低。",
    "Almost There": "差不多了",
    "Are we there yet?": "我们到那儿了吗？",
    "Big, Pink, and Useless": "巨大、粉红且毫无用处",
    "But what does it do?": "但它有什么作用呢？",
    "Can never have enough": "永远都嫌不够",
    "Capture all Shrines on Riverside": "占领河滨的所有神殿",
    "Coal Baron": "煤炭大亨",
    "Coal is the true endgame": "煤炭才是真正的终局",
    "Come to the Dark Side": "加入黑暗阵营",
    "Complete rows of 4 achievements to earn +5 bonus points per row!": "完成4行成就，每行获得+5奖励点！",
    "Crystal Breakthrough": "水晶突破",
    "Crystal Crown": "水晶王冠",
    "Crystal Peak Completionist": "水晶巅峰完成者",
    "Deuteranopia": "色盲",
    "Diggy Diggy Ore": "挖掘矿石",
    "Discover a Dig Site": "发现一个挖掘地点",
    "Each Achievement is worth 1 Achievement Point.": "每个成就值 1 个成就点。",
    "Each completed row is worth 5 bonus Achievement Points.": "每完成一行可获得 5 个奖励成就点。",
    "Emerald Empire": "翡翠帝国",
    "Fields of Green": "绿色田野",
    "Forest for the trees": "为树木而建的森林",
    "Full Metal Jacket": "全金属外壳",
    "Gonna upgrade them all": "要将它们全部升级",
    "Hall of the Mountain King": "山之国王的殿堂",
    "Happy Little Trees": "快乐的小树",
    "Have coal max storage capacity of 10,000 in Dark Forest.": "在黑暗森林中拥有最大的煤炭储存量10000。",
    "Hide completed rows": "隐藏已完成的行",
    "How many are there?": "有多少个？",
    "How much weighs the Earth?": "地球有多重？",
    "I got 99 Tiles": "我获得了99格",
    "I really like Upgrades": "我真的很喜欢升级",
    "I think we have enough fire wood now": "我想我们现在有足够的木柴了",
    "Indiana Jones is in every Game": "印第安纳·琼斯出现在每一款游戏中",
    "Industrial Revolution": "工业革命",
    "Industrialization 2.0": "工业化2.0",
    "Keep Piling em Up": "继续堆积",
    "Let's make it an even number": "让我们把它变成偶数",
    "Light-flooded Clearing": "光线充足的空地",
    "Meadows Victory": "草地胜利",
    "Melt it all down": "融化一切",
    "More Wisdom Points": "更多的智慧点数",
    "Mount Everest": "珠穆朗玛峰",
    "Mountain": "高山",
    "My favourite Tree": "我最喜欢的树",
    "Not this Again": "别再这样了",
    "On the Beach": "在海滩上",
    "Own 1 Green Crystal Formation on Crystal Peak": "拥有水晶山上的 1 个绿色晶体结构",
    "Own 1 Mountain on Dark Forest.": "在黑暗森林拥有一座山。",
    "Own 10 regular Forges on Dark Forest.": "在暗森林中拥有 10 座常规熔炉",
    "Own 100 Blue Crystal Formations on Crystal Peak": "在水晶山上拥有 100 个蓝色晶体结构",
    "Own 100 Green Crystal Formations on Crystal Peak": "在水晶山上拥有 100 个绿色晶体结构",
    "Own 100 Red Crystal Formations on Crystal Peak": "在水晶山上拥有 100 个红色晶体结构",
    "Own 3 Purple Crystal Formations on Crystal Peak": "在水晶山上拥有 3 个紫色晶体结构",
    "Own 33 White Crystal Formations on Crystal Peak": "在水晶山上拥有 33 个白色晶体结构",
    "Picky Customer": "挑剔的顾客",
    "Play on Dark Forest for 10 minutes.": "在黑暗森林玩10分钟。",
    "Praying Man": "祈祷者",
    "Pulsing Purple Power": "搏动的紫色之力",
    "Purchase all Upgrades in Crystal Peak.": "购买水晶山上的所有升级物品。",
    "Purchase an Obsidian Forge on Crystal Peak": "在水晶山上购买一座黑曜石熔炉",
    "Ready for Endgame?": "准备好终局了吗？",
    "Ready to Melt": "准备熔炼",
    "Red-Fifteen": "红十五",
    "Ruby Fields": "红宝石原野",
    "Sacred Place": "神圣之地",
    "Sapphire Sea": "蓝宝石海洋",
    "Save the Rainforests!": "拯救雨林！",
    "Scaling Up Production": "扩大生产规模",
    "Shrine Shenanigans": "神殿闹剧",
    "Smell of Napalm": "汽油弹的气味",
    "Surround a Crystal Monument without owning it": "在不拥有的情况下包围水晶纪念碑",
    "Surround a Forest without owning it": "在不拥有的情况下包围森林",
    "Surround a Mountain without owning it": "在不拥有的情况下包围山脉",
    "Surround a Shrine without owning it on Crystal Peak": "在水晶山环绕一个神殿而不拥有它",
    "Surround an Empty Land without owning it": "不拥有的情况下包围一片空地",
    "Ten Stones on a Mountain": "山上的十块石头",
    "That is a big pile": "那是一大堆",
    "The Fountain of Youth": "青春之泉",
    "The Mystic Anvil": "神秘的砧板",
    "The Solution is MOARE tiles": "解决方案是更多的方块",
    "The solution to all end-game problems": "解决所有终局问题的办法",
    "This is Wood Country": "这里是木之国度",
    "Unlock Alchemy": "解锁炼金术",
    "Upgrades are awesome": "升级太棒了",
    "Upgrades are really awesome": "升级真的很棒",
    "Vertical Limit": "垂直极限",
    "Volcanic Storage": "火山存储",
    "We can't stay here": "我们不能待在这里",
    "We have Fishies": "我们有鱼儿",
    "Wisdom Grid Unlock": "智慧网格解锁",
    "With the Power of Science": "借助科学的力量",
    "World Tree Branch": "世界之树分支",
    "World Tree Djungle": "世界之树丛林",
    "World Tree Roots": "世界之树根系",
    "World Tree Sapling": "世界之树幼苗",
    "World Tree Trunk": "世界之树树干",
    "Yes, we are ready!": "是的，我们准备好了！",
    "You are probably prestiging too much": "你可能过于自命不凡了",
    "You know, I'm rich": "你知道吗，我很富有",
    "Blacksmithing Storage": "铁匠铺存储",
    "Hardened Pickaxes": "硬化镐",
    "Increases Coal storage by 150, Iron Ore storage by 150, and Iron Ingots storage by 450": "使煤炭存储量增加 150，铁矿石存储量增加 150，铁锭存储量增加 450",
    "Increases Iron Ingots storage by 50 per Empty Land owned": "拥有的每块空地，都使铁锭存储量增加 50",
    "Iron Ingot Warehousing": "铁锭仓库",
    "Save often to avoid losing progress!": "经常保存以避免丢失进度！",
    "Wood Storage Scaling": "木头仓库扩容",
    "Forging...": "锻造中...",
    "Inputs Required:": "输入要求:",
    "Outputs:": "输出:",
    "Iron Ingots": "铁锭",
    "more": "更多",
    "Iron Ingots": "铁锭",
    "Reset Now": "立即重置",
    "Show Wisdom Grid": "显示智慧网格",
    "Stone Storage Scaling": "石头存储扩展",
    "The grid extends in all directions - keep exploring!": "网格向各个方向延伸——继续探索吧！",
    "Wisdom Points gained is based on the amount of Tiles owned in the current run": "本轮游戏所拥有的方块数量决定了获得的智慧点",
    "Wisdom Points on Reset": "重置可获得智慧点",
    "Cave Spelunking": "洞穴探险",
    "Digging in Shifts": "轮班挖掘",
    "Forest tile cost is 20% cheaper": "森林方块成本便宜20%",
    "Gain 10 Iron Ore every 18 seconds": "每 18 秒获得 10 个铁矿石",
    "Gain 8 Stone every 7 seconds and 9 Iron Ore every 7 seconds": "每7秒获得8石头，每7秒获得9铁矿石",
    "Increases Coal storage by 175, Iron Ore storage by 175, and Iron Ingots storage by 550": "煤炭储存量增加 175，铁矿石储存量增加 175，铁锭储存量增加 550",
    "Increases Iron Ingots storage by 500 per Forge owned": "每个锻炉增加500个铁锭储存",
    "Industrial Juggernaut": "工业巨兽",
    "Lid of a Cola Bottle": "可乐瓶盖",
    "Mechanized Forestry": "林业机械化",
    "Quarry tile cost is 20% cheaper": "采石场方块成本降低了20%",
    "Ranger Patrols": "护林员巡逻",
    "Sell off worthless Relics": "出售无用的遗物",
    "Steam-powered Mining Machinery": "蒸汽动力采矿机械",
    "Strip Mining": "露天采矿",
    "Optimized Transport Routes": "优化运输路线",
    "Coal Compacting": "煤炭压缩",
    "Gain 10 Wood every 3 seconds, 10 Stone every 3 seconds, and 10 Coal every 3 seconds": "每3秒获得10木头，每3秒获得10石头，每3秒获得10煤炭",
    "Increases Coal storage by 1,000": "煤炭储存量增加 1000",
    "Universal Income": "全民收入",
    "Ancient Timber Bounty": "古老的木头馈赠",
    "Quarrykeepers Plenty": "采石场看守者的丰饶",
    "spent": "花费",
    "⭐ Grid Upgrades": "⭐ 网格升级",
    "💎 Wisdom Points": "💎 智慧点数",
    "🔄 Prestige": "🔄 声望",
    "📊 Tiles Owned": "📊 拥有方块",
    "Wisdom Grid": "智慧网格",
    "Wisdom Points": "智慧点数",
    "Wisdom Points. Only adjacent tiles can be purchased.": "智慧点数。只能购买相邻的方块。",
    "pending": "等待中",
    "Acquiring new Wisdom Bonus tiles will reset your current run.": "获取新的智慧奖励方块将重置当前的运行状态。",
    "Advanced Supply Lines": "高级补给线",
    "Auto-Upgrades": "自动升级",
    "Automation Upgrade": "自动化升级",
    "Bigger Equals Better": "越大越好",
    "Charcoal Burners": "木炭燃烧器",
    "Complete a prestige run to earn Wisdom Points based on tiles owned. Use Wisdom Points to unlock permanent upgrades in this grid.": "完成一次声望运行，根据所拥有的方块获得智慧点。使用智慧点数在该网格中解锁永久性升级。",
    "Each Wisdom Bonus costs": "每个智慧加成成本",
    "Every 10 seconds gain Coal, Iron Ore, and Iron Ingots equal to the count of owned Mountains x Shrines x Dig Sites. If any of these three are 0, you gain no resources.": "每 10 秒会获得与所拥有的山脉数量、神殿数量和挖掘点数量相乘的煤炭、铁矿石和铁锭数量相同的资源。如果这三者中任何一个为 0，则不会获得任何资源。",
    "Every 10 seconds, gain 5% of maximum storage worth of whatever basic resource (wood, stone, coal, iron ore) you have the least of.": "每 10 秒，根据你所拥有的最少的基本资源（木头、石头、煤炭、铁矿石）的总量的 5%获得相应资源的存储量的值。",
    "Expeditionary Force": "远征力量",
    "Filling in the gaps": "填补空白",
    "Forester": "护林员",
    "Fully Stocked": "储备充足",
    "Gain +1000 Stone per second if your current Stone is below 3000 and your Stone storage capacity exceeds 30000.": "如果你的当前石头低于3000并且你的石头存储容量超过30000，每秒获得+1000石头。",
    "Gain +1000 Wood per second if your current Wood is below 3000 and your Wood storage capacity exceeds 30000.": "如果你的当前木头低于3000并且你的木头储存容量超过30000，每秒获得+1000木头。",
    "Generate 5 Artifacts and 5 Iron Ingots per second for each Shrine tile you own.": "您拥有的每个神殿格子每秒可生成 5 件神器和 5 个铁锭。",
    "Green Thumb": "园艺专家",
    "Hallowed Grounds": "圣地",
    "Halves the cost of purchasing Mountain tiles.": "购买山地格子的成本减半。",
    "Headstart": "领先优势",
    "Heretic Practices": "异端行为",
    "How Wisdom Works": "智慧如何运作",
    "Immediate Amortisation": "即时摊销",
    "Increase storage capacity for Wood, Stone, Coal, Iron Ore, and Iron Ingots by +200 per second for the first 5 minutes of each run.": "在每次运行的前 5 分钟内，木头、石头、煤炭、铁矿石和铁锭的存储容量每秒增加 200 个单位。",
    "Increase the maximum storage of Wood, Stone, Coal, and Iron Ore by 2500 and start all runs with the maximum value of these resources.": "将木头、石头、煤炭和铁矿石的最大存储量增加 2500 个单位，并在每次运行时将这些资源的初始值设置为最大值。",
    "Infinite Stone": "无限的石头",
    "Infinite Wood": "无限的木头",
    "Inflatable Shelves": "可充气货架",
    "Legacy Excavation": "遗物挖掘",
    "Mining Operations": "采矿作业",
    "Mountaineering Club": "登山俱乐部",
    "Necessity is the mother of invention": "必要性是发明之母",
    "No brakes on this crazy train": "这列疯狂的列车没有刹车",
    "Purchase Wisdom Bonuses to enhance your future runs on this map.": "购买智慧加成以增强您在该地图上的未来运行效果。",
    "Purchasing regular Upgrades no longer deducts resources.": "购买常规升级不再消耗资源。",
    "Rapid Development Mandate": "快速发展任务",
    "Reduce the purchase cost of all tiles by 33%.": "将所有格子的购买成本降低 33%。",
    "Requires 100 owned tiles. Spend up to 75% of available resources to auto-buy any affordable tiles prioritizing tiles that are closer to the starting location.": "需要 100 个已拥有的格子。花费最多 75%的可用资源自动购买任何可负担的格子，优先购买距离起始位置较近的格子。",
    "Requires 40000 max storage for Wood, Stone, Coal, Iron Ore, and Iron Ingots. Gain 3% of maximum storage capacity worth of these resources every 4 seconds.": "需要木头、石头、煤炭、铁矿石和铁锭的最大存储量为 40000。每 4 秒获得这些资源最大存储容量 3%的价值。",
    "Sand Shovels": "沙铲",
    "Shift-click an Upgrade to skip confirmation.": "使用 Shift 键点击升级可跳过确认。",
    "Spend up to 50% of available resources to auto-buy Quarries.": "花费最多 50%的可用资源自动购买矿场。",
    "Start each run with all Shrine tiles already in your possession.": "每次运行时，将所有神殿格子先收入囊中。",
    "Start each run with the 8 surrounding tiles already purchased.": "每次运行时，先购买周围 8 个格子。",
    "Supply Lines": "供给线",
    "Ultimate Synergy": "终极协同效应",
    "Upgrades marked with this icon unlock new automations that automatically purchase tiles or upgrades for you.": "带有此图标标记的升级将解锁新的自动化功能，这些功能会自动为你购买方块或升级物品。",
    "Automatically buy Upgrades once they become affordable.": "一旦升级成本变得可以承受，系统会自动为您购买升级。",
    "Every tile you own produces +0.5 Stone per second on top of existing effects.": "您拥有的每一块地都会额外每秒产出 0.5 块石头（在此基础上还会叠加现有效果）。",
    "Every tile you own produces +0.5 Wood per second on top of existing effects.": "您拥有的每一块地都会额外每秒产出 0.5 块木料（在此基础上还会叠加现有效果）。",
    "Gain +1 Iron Ingot every second for free without having to have Forges or spend Coal or Iron Ore.": "您将免费每秒获得 1 个铁锭，无需拥有熔炉或花费煤炭或铁矿石。",
    "Spend up to 50% of available resources to auto-buy a Forests.": "您可以花费最多 50% 的可用资源自动购买森林。",
    "Spend up to 50% of available resources to auto-buy Coal Deposits and Forges.": "您可以花费最多 50% 的可用资源自动购买煤矿矿床和熔炉。",
    "Spend up to 50% of available resources to auto-buy Iron Mines and Empty Lands.": "您可以花费最多 50% 的可用资源自动购买铁矿和空地。",
    "Spend up to 75% of available resources to auto-buy the most expensive affordable tile every 10 seconds.": "您可以花费最多 75% 的可用资源每 10 秒自动购买最昂贵且可承受的方块。",
    "Tripples the chance to find a Dig Site and increases Artifacts storage capacity by 20,000.": "这会增加发现挖掘点的几率，并将遗物存储容量增加 20，000。",
    "Your starting Tent produces 2 Wood, Stone, Coal, and Iron Ore every second.": "您的初始帐篷每秒会产出 2 块木料、石头、煤炭和铁矿石。",
    "Gain 100 Wood every 4 seconds, 100 Stone every 4 seconds, and 100 Coal every 4 seconds": "每 4 秒获得 100 树木，每 4 秒获得 100 石头，每 4 秒获得 100 煤炭",
    "How to Get More Wisdom:": "如何获取更多智慧：",
    "Marketplace Trading": "市场交易",
    "Non-Linear Scaling:": "非线性扩展：",
    "Supply Runs": "供应运行",
    "Wisdom Points grow progressively with more tiles owned. The formula is a mix of square root and linear components.": "智慧点数会随着所拥有方块数量的增加而逐步增加。其公式是根号和线性成分的混合。",
    "You only earn Wisdom when you surpass your personal best tile count from previous runs. Prestiging at the same or lower tile count grants no additional Wisdom.": "只有当您超过之前运行中的个人最高方块数量时，才能获得智慧。在相同或更低的方块数量下获得声望不会获得额外的智慧。",
    "Extra Coal Storage": "额外煤炭储存",
    "Gain 250 Wood every 5 seconds, 250 Stone every 5 seconds, and 250 Coal every 5 seconds": "每 5 秒增加 250 木头、250 石头和 250 煤炭",
    "Increases storage capacity of all resources by 2 every second (caps at 20,000)": "所有资源的储存容量每秒增加 2（上限为 20，000）",
    "Iron Ingot Mass Production": "铁锭批量生产",
    "Iron Ore Compacting": "铁矿石压缩",
    "Prestige bonuses stack multiplicatively - they become very powerful!": "声望加成进行累加计算——效果会非常强大！",
    "The Prestige system allows you to reset your progress for permanent bonuses.": "声望系统允许你重置你的进度以获得永久奖励。",
    "🏛️ Dig Site Discovered!": "🏛️ 发现挖掘点！",
    "Reinforced Concrete Warehouses": "钢筋混凝土仓库",
    "Waiting...": "等待中...",
    "Endless Vaulted Cellars": "无尽的拱形地窖",
    "An ancient archaeological site has been unearthed": "一个古老的考古遗址被发掘出来了",
    "Archaeology Work Crew Integration": "考古工作团队整合",
    "Artifact Compacting": "神器压缩",
    "Artifact Smuggling Ring": "神器走私团伙",
    "Artifacts": "神器",
    "Big Black Pile": "大型黑色矿堆",
    "Increases Iron Ingots storage by 1,000 per Mountain owned and Artifacts storage by 100 per Mountain owned": "拥有一座山时，铁锭存储量增加 1000，神器存储量增加 100",
    "Increases storage capacity of all resources by 3 every second (caps at 30,000)": "所有资源的存储容量每秒增加 3（上限为 30000）",
    "Increases Wood storage by 10,000, Stone storage by 10,000, and Coal storage by 10,000": "木头存储量增加 10000，石头存储量增加 10000，煤炭存储量增加 10000",
    "Mountain Fortress": "山地堡垒",
    "Too Big To Fail": "大而不倒",
    "Underground Logistics Network": "地下物流网络",
    "An archaeological excavation site that uses 1 Wood + 1 Iron Ingot to excavate 1 Artifact every second": "一个考古挖掘场地，每秒使用 1 份木头和 1 个铁锭来挖掘 1 件神器",
    "Auto Mountains": "自动山脉",
    "Auto-Mountains": "自动山脉",
    "Burn It All To Ash": "将一切化为灰烬",
    "Converts 1 Wood + 1 Iron Ingots → 1 Artifacts/sec": "将 1 份木头 + 1 个铁锭转换为 1 件神器/秒",
    "Dig Site": "挖掘地点",
    "Excavating...": "挖掘中...",
    "Gold Plated Vaults": "镀金宝库",
    "Idle...": "空闲...",
    "Increases Artifacts storage by 500 per Shrine owned": "每拥有一个神殿，增加500件神器的储存",
    "Secured Vaults": "安全宝库",
    "Shrine Ornaments": "神殿装饰品",
    "The Black Vault": "黑色宝库",
    "Ultimate Underground Logistics Network": "终极地下物流网络",
    "We need even MOARE Iron!": "我们需要更多的铁矿石！",
    "We need even more Iron!": "我们需要更多的铁矿石！",
    "We need more Iron!": "我们需要更多的铁矿石！",
    "You Made Lava": "你制造了熔岩",
    "Off": "关闭",
    "Hard Reset": "硬重置",
    "Force Save": "强制保存",
    "Danger Zone": "危险区",
    "English": "英语",
    "BETA": "测试",
    "Affordable tile highlighting": "高亮高性价比方块",
    "Animated (default)": "动画（默认）",
    "Auto-camera (automatic zoom adjustment)": "自动摄像机（自动调整缩放比例）",
    "Auto-Camera Switch Threshold: 80%": "自动摄像机切换阈值：80%",
    "Auto-purchase Mountain every 1 second using 100% of available resources": "每秒自动使用全部可用资源购买山脉一次（消耗 100% 资源）",
    "Compact left menu buttons": "紧凑的左侧菜单按钮",
    "Compact right menu buttons": "紧凑的右菜单按钮",
    "Gameplay": "游戏玩法",
    "Interface": "界面",
    "Save Management": "保存管理",
    "Savegame": "保存游戏",
    "Show achievement pop-ups": "显示成就弹出窗口",
    "Show language selector": "显示语言选择器",
    "Show tile acquisition animations": "显示贴图获取动画",
    "Static": "静态",
    "When map ownership reaches this percentage, camera will focus on unowned tiles instead of owned tiles": "当地图所有权达到这个百分比时，相机将聚焦在无主的方块上，而不是拥有的方块上",
    "You can also press Ctrl+S to save": "您还可以按 Ctrl+S 键进行保存。",
    "Confirm Reset": "确认重置",
    "All achievements": "全部成就",
    "All map completions": "所有地图的完成情况",
    "Saved!": "已保存!",
    "⚠️ Hard Reset Warning ⚠️": "⚠️ 硬重置警告 ⚠️",
    "All resources and tiles": "所有资源和方块",
    "Atlas and World Tree progress": "地图集和世界树进度",
    "I understand that devs, admins, and mods can not restore my progress.": "我明白开发者、管理员和插件不能恢复我的进度。",
    "I understand this will delete ALL progress and that there is no undo button.": "我明白这将删除所有进度，并且没有撤销按钮。",
    "This action cannot be undone! This action is irreversible!": "此操作无法撤销！这一行动是不可逆转的！",
    "This action will permanently delete ALL progress setting you back to square one including:": "此操作将永久删除您所有的设置，将您重新还原至初始状态，包括：",
    "Auto Tiles": "自动方块",
    "🌳 World Tree (": "🌳 世界树 (",
    "🎉 Map Complete! 🎉": "🎉 地图完成! 🎉",
    "🔄 Replay": "🔄 重玩",
    "🗺️ Atlas": "🗺️ 地图集",
    "Atlas": "地图集",
    "Continue": "继续",
    "Max Wisdom Points reached for this map!": "在本地图中已获得最大智慧点数！",
    "Congratulations! You've earned 5 Globes for completing Meadows for the 1st time!": "恭喜！你已经获得了5个球体，因为第一次完成了 草地 地图！",
    "Frugal Conquest\n\nManual tile purchases have a chance to be free. Starts at 5% and increases by 5% each time it fails, resetting on success.\n\n🔒 Locked": "节俭征服\n\n购买单个方块有几率是免费的。初始为 5%，每次失败时增加 5%，成功后重置。\n\n🔒 未解锁",
    "Globes": "球体",
    "Globes Spent": "已使用的球体",
    "Nodes Unlocked": "节点解锁",
    "Spend Globes to unlock permanent bonuses that persist across all runs. Earn additional Globes by completing maps on the Atlas.": "花费球体来解锁永久性奖励，这些奖励在所有游戏过程中都会持续生效。通过完成图谱表中的地图可获得额外的球体。",
    "World Tree": "世界树",
    "Runs": "轮次",
    "Maps Explored": "已探索地图",
    "Fit": "回正",
    "Globes Available": "可用球体",
    "Completed Runs": "已完成轮次",
    "Atlas Progress": "地图集进度",
    "Complete maps to earn Globes. Globes can be spent on the World Tree for permanent bonuses.": "完成地图即可获得球体。球体可用于在世界之树上兑换永久加成效果。",
    "Rapid Upgrade Protocols\n\nEnhances the Auto-Upgrades Wisdom Grid feature. Reduces interval by 5x and purchases 2 upgrades per interval (10x total improvement). Requires the Auto-Upgrades Wisdom Grid node to have an effect.\n\n🔒 Locked": "快速升级协议\n\n增强了“自动升级智慧网格”功能。将间隔时间缩短 5 倍，并且每个间隔可购买 2 次升级（总计提升 10 倍）。需要“自动升级智慧网格”节点生效。\n\n🔒 未解锁",
    "Bountiful Harvest\n\nAfter purchasing any tile, gain 5% of max storage worth of a random resource from that tile's cost. Works with manual purchases and auto-buyers.\n\n🔒 Locked": "大丰收\n\n购买任意方块后，从该方块的成本中获得随机资源，价值为最大存储量的5%。适用于手动购买和自动购买。\n\n🔒 未解锁",
    "Converter Toggle\n\nAdds a master toggle to turn Forges and other converters on or off. Works on all maps with all tile types that convert resources.\n\n🔒 Locked": "转换器开关\n\n添加一个主开关，用于打开或关闭锻造设施和其他转换器。适用于所有地图上所有可转换资源的方块类型。\n\n🔒 未解锁",
    "Crystal Starter Pack\n\nStart each Crystal Peak run with 100 Red, Blue, Green, and White Crystals.\n\nNote: This bonus only applies to Crystal Peak runs.\n\n🔒 Locked": "水晶新手包\n\n每次进入水晶峰时，携带100个红色、蓝色、绿色和白色水晶。\n\n注意：此奖励仅适用于水晶峰。\n\n🔒 未解锁",
    "Dark Forest Wood Income\n\nProduces 100 wood per second while playing on the Dark Forest map. This bonus only applies to Dark Forest and does not affect other maps.\n\n🔒 Locked": "黑暗森林木头收益\n\n在黑暗森林地图上游戏时，每秒产出100木头。此加成仅适用于黑暗森林地图，不影响其他地图。\n\n🔒 未解锁",
    "Improved Tile Queue\n\nIncreases tile queue capacity from 3 to 7.\n\n🔒 Locked": "改进的方块队列\n\n方块队列容量从3增加到7。\n\n🔒 未解锁",
    "Tile Purchase Queue\n\nDouble-click tiles to queue them for automatic purchase. Queue up to 3 tiles.\n\nCost: 5 Globes": "方块购买队列\n\n双击方块以将其加入自动购买队列。最多可排队3个方块。\n\n成本：5个球体",
    "Ultimate Supply Lines\n\nMultiplies the periodic resource production from Supply Lines (Wisdom Grid) by 10, increasing from 2 to 20 resources per tick.\n\nCost: 2 Globes": "终极补给线\n\n将补给线（智慧网格）的周期性资源产量乘以10，每刻增加的资源从2个增加到20个。\n\n消耗：2个球体",
    "A riverside settlement awaits. Gentle waters flow through fertile land, offering stone-rich banks and the promise of prosperity. Build along the water's edge and harness the river's bounty.": "一处沿河而建的村落正等待着人们前来。清澈的水流经肥沃的土地，岸边布满了富含石头的土壤，还蕴含着繁荣的希望。沿着河边建设，充分利用河流的资源吧。",
    "A land of plenty awaits your first settlement. Forests rustle with harvest-ready timber. Quarries yield ancient stone. Iron hides in the hills, coal smolders in forgotten veins, and shrines crown the peaks. The air carries the scent of pine and possibility. Here you will raise your tent, light your forge, and begin your empire. The meadows give freely—but only to those who take. Master this land, earn your wisdom, and prepare for what lies beyond.": "一片富饶的土地正等待着您的首次定居。森林中树木郁郁葱葱，已成熟待采。矿场产出古老的石头。山间蕴藏着铁矿，深埋的煤层在岁月的遗忘中散发着微光，山峰之上矗立着神殿。空气中弥漫着松木的香气和无限的可能。在这里，您将搭建帐篷，点亮熔炉，开启您的帝国征程。这片草地慷慨地提供资源——但只会给予那些勇于索取的人。掌控这片土地，积累智慧，为前方的未知做好准备。",
    "Sunlight never touches the Sylvan Deep. Towering trees with iron-dark bark block the sky, making noon feel like midnight. The cold air hangs thick with the scent of moss and mystery. But darkness has its rewards. Dark forests yield three times the Wood. Umbral Forges transmute common Wood into precious Stone, Coal, and Iron Ore. The shadows conceal both danger and power. Only those who have proven themselves should dare to build here—and reap what the darkness offers.": "阳光永远无法触及幽林深处。高耸的树木，其树皮呈铁黑色，遮蔽了天空，使得正午的时光仿佛已是午夜。冰冷的空气弥漫着苔藓和神秘的气息。但黑暗也有其回报。幽暗的森林产出的木头是普通森林的三倍。暗影熔炉将普通的木头转化为珍贵的宝石、煤炭和铁矿石。阴影中隐藏着危险与力量。只有那些已经证明自己的人才敢在此建造——并收获黑暗所给予的一切。",
    "Hard": "困难",
    "Medium": "中等",
    "Map Size": "地图大小",
    "Very Large": "非常大",
    "Return to Game": "返回游戏",
    "Return to Atlas": "返回地图集",
    "Globes Sealed": "封印的球体",
    "Easy": "简单",
    "Difficulty": "难度",
    "Chapter": "章节",
    "Begin New": "开始新一轮",
    "Begin new Chapter": "开始新章节",
    "Fastest Completion": "最快完成时间",
    "After Purchase:": "地图集购买:",
    "Confirm": "确认",
    "Cost:": "成本:",
    "Current Globes:": "当前球体:",
    "Ultimate Supply Lines": "终极补给线",
    "Tile Purchase Queue": "方块购买队列",
    "Purchase Upgrade?": "购买升级?",
    "Double-click tiles to queue them for automatic purchase. Queue up to 3 tiles.": "双击方块即可将其添加到自动购买列表中。最多可添加 3 个方块到该队列中。",
    "Multiplies the periodic resource production from Supply Lines (Wisdom Grid) by 10, increasing from 2 to 20 resources per tick.": "将来自供应线（智慧网格）的周期性资源生产乘以10，每 Tick 从2增加到20资源。",
    "Dark Forest Wood Income\n\nProduces 100 wood per second while playing on the Dark Forest map. This bonus only applies to Dark Forest and does not affect other maps.\n\nCost: 1 Globes": "在黑暗森林地图上玩游戏时，每秒产生100块木头。此加成仅适用于暗森林地图，对其他地图无效。\n\n成本：1 球体",
    "Crystal Starter Pack": "水晶入门包",
    "Dark Forest Wood Income": "黑暗森林木头收入",
    "Crystal Starter Pack\n\nStart each Crystal Peak run with 100 Red, Blue, Green, and White Crystals.\n\nNote: This bonus only applies to Crystal Peak runs.\n\nCost: 1 Globes": "水晶入门包\n\n每次进行水晶山轮次时，初始将获得 100 颗红色、蓝色、绿色和白色的水晶。\n\n注意：此奖励仅适用于水晶山轮次。\n\n成本：1 球体",
    "Produces 100 wood per second while playing on the Dark Forest map. This bonus only applies to Dark Forest and does not affect other maps.": "在黑暗森林地图上玩的时候，每秒产生100个木头。这个加成只对黑暗森林有效，对其他地图无效。",
    "Start each Crystal Peak run with 100 Red, Blue, Green, and White Crystals.\n\nNote: This bonus only applies to Crystal Peak runs.": "每次进行水晶山轮次时，初始将获得 100 颗红色、蓝色、绿色和白色的水晶。\n\n注意：此奖励仅适用于“水晶峰”任务。",
    "Ultimate Supply Lines\n\nMultiplies the periodic resource production from Supply Lines (Wisdom Grid) by 10, increasing from 2 to 20 resources per tick.\n\nOwned": "终极补给线\n\n将补给线（智慧网格）的定期资源产出乘以 10，从每回合 2 单位资源增加到 20 单位资源。\n\n已拥有",
    "Bountiful Harvest\n\nAfter purchasing any tile, gain 5% of max storage worth of a random resource from that tile's cost. Works with manual purchases and auto-buyers.\n\nCost: 4 Globes": "大丰收\n\n购买任意一块方块后，将从该方块的成本中获得相当于其最大存储量 5% 的随机资源。此效果适用于手动购买和自动购买模式。\n\n花费：4 球体",
    "Rapid Upgrade Protocols\n\nEnhances the Auto-Upgrades Wisdom Grid feature. Reduces interval by 5x and purchases 2 upgrades per interval (10x total improvement). Requires the Auto-Upgrades Wisdom Grid node to have an effect.\n\nCost: 4 Globes": "快速升级协议\n\n增强了“自动升级智慧网格”功能。将间隔时间缩短 5 倍，并且每间隔可购买 2 次升级（总计提升 10 倍）。需要“自动升级智慧网格”节点生效。\n\n费用：4 球体",
    "Dark Forest Wood Income\n\nProduces 100 wood per second while playing on the Dark Forest map. This bonus only applies to Dark Forest and does not affect other maps.\n\nOwned": "暗黑森林木头收入\n\n在暗黑森林地图上游玩时，每秒产出100木头此加成仅适用于暗森林地图，对其他地图无效。\n\n已拥有",
    "Crystal Starter Pack\n\nStart each Crystal Peak run with 100 Red, Blue, Green, and White Crystals.\n\nNote: This bonus only applies to Crystal Peak runs.\n\nOwned": "水晶入门包\n\n每次进行水晶山轮次时，初始将拥有 100 颗红色、蓝色、绿色和白色的水晶。\n\n注意：此奖励仅适用于水晶山地图。\n\n已拥有",
    "Your starting Tent produces 20 Wood, Stone, Coal, and Iron Ore every second.": "您的初始帐篷每秒能产出 20 木头、石头、煤炭和铁矿石。",
    "All resources": "所有资源",
    "All run upgrades": "所有轮次升级",
    "Wisdom Grid for this map": "此地图的智慧网格",
    "All tiles and grid progress": "所有方块和网格进度",
    "Atlas progress and World Tree upgrades will be preserved.": "地图集的进展和世界树的升级将被保留。",
    "Start Riverside?": "开始河畔?",
    "Starting this map will reset:": "开始此地图将重置:",
    "Tip: Shift-click to skip this confirmation next time.": "提示：下次若要跳过此确认步骤，请按住 Shift 键并点击。",
    "Version": "版本",
    "Buy me a Coffee": "请作者喝杯咖啡",
    "Contact & Social": "联系 & 社交",
    "Email:": "电子邮箱:",
    "Developer:": "开发者:",
    "About Idle-Squares": "关于 方块放置",
    "PayPal Me": "PayPal",
    "Special Thanks": "特殊感谢",
    "Support Development": "支持开发",
    "This game is completely free to play. If you want to throw your hard earned money at me, you can do so here:": "这款游戏完全免费游玩。如果你想把你辛苦赚来的钱扔给我，你可以在这里这样做：",
    "Join Idle-Squares Official Discord Server": "加入 方块放置 官方Discord服务器",
    "Idle-Squares Official": "方块放置官方",
    "Here you can discuss the game with fellow idle addicts, post feedback, bugs, and suggestions.": "在这里，您可以与同样沉迷于此的游戏爱好者们交流心得，发表反馈意见、指出漏洞并提出建议。",
    "A dense dark forest that produces 3 Wood per second": "一片茂密幽暗的森林，每秒能产出 3 份木头",
    "Coal Deposit tile cost is 50% cheaper": "煤矿床方块的价格降低了 50%",
    "Coal Stockpile Expansion": "煤炭储备扩充",
    "Increases Coal storage by 1 every 1 second (caps at +500 total)": "每秒增加 1 单位煤炭储存量（总量上限为 +500）",
    "Iron Mine tile cost is 50% cheaper": "铁矿方块的价格降低了 50%",
    "Mining Infrastructure": "采矿基础设施",
    "Quarry tile cost is 50% cheaper": "采石场方块的价格降低了 50%",
    "Riverside Masonry": "河滨砌筑",
    "Coming Soon": "即将推出",
    "Dark Forest tile cost is 50% cheaper and Forest tile cost is 50% cheaper": "暗森林方块价格便宜 50%，森林方块价格也便宜 50%",
    "Docks Infrastructure": "港口基础设施",
    "Forestry Management": "林业管理",
    "Forge World": "锻造世界",
    "Grand Ranger": "大护林员",
    "Inland Waterway Transport": "内陆水路运输",
    "Maritime Ingot Transport": "海上锭子运输",
    "Midland Trade Routes": "中部贸易路线",
    "Sea Access": "海上通道",
    "Seafaring Nation": "航海国家",
    "Summit Pilgrims": "峰顶朝圣者",
    "Urbanisation": "城市化",
    "Wandering Miners": "流浪矿工",
    "Increases Wood storage by 1 every 1 second (caps at +400 total), Iron Ore storage by 1 every 1 second (caps at +400 total), and Iron Ingots storage by 1 every 1 second (caps at +400 total)": "每秒增加木头储存量 1 个单位（总上限为 +400），每秒增加铁矿石储存量 1 个单位（总上限为 +400），每秒增加铁锭储存量 1 个单位（总上限为 +400）",
    "Bridge Engineering": "桥梁工程",
    "Carbon Survey": "碳含量调查",
    "Dark Forge Efficiency": "暗铸厂效率提升",
    "Dark Forge tile cost is 50% cheaper": "暗铸厂的矿石成本降低 50%",
    "Expanding Warehouses": "扩建仓库",
    "Forest Survey": "森林调查",
    "Forest tile cost is 50% cheaper": "森林矿石成本降低 50%",
    "Gain 4 Stone every 1 second and 4 Coal every 1 second": "每1秒获得4个石头和4个煤",
    "Increases Wood storage by 5 every 1 second (caps at +1,000 total)": "每秒增加木头储存量 5（上限为总计 1000）",
    "Industrial Base Materials": "工业基础材料",
    "River tile cost is 50% cheaper": "河流矿石成本降低 50%",
    "Riverbanks tile cost is 50% cheaper": "河岸矿石成本降低 50%",
    "Timber Reserve": "木头储备",
    "Umbral Acquaintance": "暗影相识",
    "All owned tiles will be reset": "所有拥有的方块将被重置",
    "All resources will be reset": "所有资源将被重置",
    "All Upgrades will be reset": "所有升级都将被重置",
    "Confirm Prestige": "确认声望",
    "Some of your progress will be reset:": "您的部分进度将被重置：",
    "Wisdom Bonuses will NOT be reset.": "智慧加成将不会被重置。",
    "Confirm Purchase": "确认购买",
    "Continue?": "继续?",
    "Owned": "已拥有",
    "At the start of each run, Forges and Dark Forges are placed along the river corridors above the thin river and below the wide river.": "每次运行开始时，锻造台和黑暗锻造台会分别放置在河流走廊的上方（位于狭窄河流的上方）和下方（位于宽阔河流的下方）。",
    "Coming Soon - This upgrade has not been implemented yet": "即将到来-这个升级还没有实现",
    "Every 2 seconds, gain Wood equal to the number of regular Upgrades purchased in this run.": "每 2 秒，将获得与本次运行中购买的常规升级数量相等的木材。",
    "Every 20 seconds, gain Iron Ingots equal to Achievement Points times the number of River and Riverbank tiles you own.": "每 20 秒，将获得与成就点数乘以您拥有的河流和河岸格子数量相等的铁锭。",
    "Every tile you own that is not a Forest or Dark Forest increases the storage capacity of Stone, Coal, Iron Ore, Iron Ingots, and Artifacts by +75.": "您拥有的每一块非森林或黑暗森林的格子都会使石头、煤炭、铁矿石、铁锭和神器的存储容量增加 +75。",
    "Gain 1 Iron Ore and 1 Coal per second for every Riverbank you own.": "每拥有一块河流岸格子，您每秒将获得 1 个铁矿石和 1 个煤炭。",
    "Purchasing  will reset your current run when you close this window.": "关闭此窗口时，购买操作将重置当前运行。",
    "Spend 100% of available resources to auto-buy Riverbanks and Rivers every second.": "每秒花费 100% 的可用资源自动购买河流岸格子和河流。",
    "Spend up to 100% of available resources to auto-buy Empty tiles, Mountains, and Shrines (one of each per second).": "每秒最多花费 100% 的可用资源自动购买空格子、山脉和神庙（每秒各一个）。",
    "Spend up to 100% of available resources to auto-buy Forests and Dark Forests.": "每秒最多花费 100% 的可用资源自动购买森林和黑暗森林。",
    "Spend up to 100% of available resources to auto-buy Forge and Dark Forge tiles every 3 seconds.": "每 3 秒最多花费 100% 的可用资源自动购买锻造台和黑暗锻造台格子。",
    "Spend up to 75% of available resources to auto-buy Coal Deposits, Quarries, and Iron Mines (one of each per second).": "每秒最多花费 75% 的可用资源自动购买煤炭矿床、采石场和铁矿（每秒各一个）。",
    "Start each run with a path to the nearest riverbank already owned, plus the 8 surrounding tiles at both start and riverbank.": "每次开始游戏时，都要先选择一条已拥有的通往最近河岸的路径，同时还要选定起始位置以及河岸两侧的 8 个相邻格子。",
    "A mysterious dark forge that transmutes 50 Wood into 20 Stone + 15 Coal + 10 Iron Ore per second": "一个神秘的黑暗熔炉，每秒可以将 50 木头变成 20 石头 + 15块 煤 + 10 铁矿石",
    "Converts 50 Wood → 20 Stone + 15 Coal + 10 Iron Ore/sec": "每秒把50块木头转换为 → 20 石头+ 15 煤+ 10 铁矿石",
    "Dark Forge": "黑暗熔炉",
    "Sleeping...": "睡眠中...",
    "Transmuting...": "转化中...",
    "River": "河流",
    "A mystical waterway that requires wood to maintain its bridges, ferry crossings, and riverside docks": "一条神秘的水道，需要木材来维护其桥梁、渡口和河岸码头",
    "A riverbank that produces Stone from the flowing water": "一条能从流动的水中产出石头的河岸",
    "Coal Accumulator": "煤炭储存器",
    "Drains 2 Wood/sec": "每秒排水 2 个木材",
    "Increases Coal storage by 5 every 1 second (caps at +1,000 total)": "每 1 秒增加煤炭储存量 5（上限为 +1000 总量）",
    "Increases Iron Ingots storage by 5 every 1 second (caps at +1,000 total)": "每 1 秒增加铁锭储存量 5（上限为 +1000 总量）",
    "Increases Iron Ore storage by 5 every 1 second (caps at +1,000 total)": "每 1 秒增加铁矿石储存量 5（上限为 +1000 总量）",
    "Increases Stone storage by 5 every 1 second (caps at +1,000 total)": "每 1 秒增加石头储存量 5（上限为 +1000 总量）",
    "Ingot Vault": "锭库",
    "Iron River Smelting": "铁河熔炼",
    "Mason's Hoard": "石匠宝库",
    "Ore Silo": "矿石筒仓",
    "Riverbank": "河岸",
    "Riverwood Grove": "河木丛林",
    "Sacred Site Survey": "圣地勘测",
    "Shoreline Prospecting": "海岸线勘探",
    "Shoreline Survey": "海岸线调查",
    "Shrine tile cost is 40% cheaper": "神殿方块成本降低 40%",
    "Auto Upgrades": "自动升级",
    "Congratulations! You've earned 4 Globes for completing Riverside for the 1st time!": "恭喜！恭喜您首次通关“河畔”，获得 4 球体！",
    "Enhances the Auto-Upgrades Wisdom Grid feature. Reduces interval by 5x and purchases 2 upgrades per interval (10x total improvement). Requires the Auto-Upgrades Wisdom Grid node to have an effect.": "增强了“自动升级智慧网格”功能。将间隔时间缩短 5 倍，并且每间隔一次可购买 2 次升级（总计提升 10 倍）。此功能需要“自动升级智慧网格”节点生效。",
    "After purchasing any tile, gain 5% of max storage worth of a random resource from that tile's cost. Works with manual purchases and auto-buyers.": "购买任何一块方块后，将从该方块的费用中获得相当于其最大存储量 5% 的随机资源。此效果适用于手动购买和自动购买模式。",
    "Bountiful Harvest": "大丰收",
    "Bountiful Harvest\n\nAfter purchasing any tile, gain 5% of max storage worth of a random resource from that tile's cost. Works with manual purchases and auto-buyers.\n\nOwned": "大丰收\n\n购买任意一块方块后，将从该方块的成本中获得相当于其最大存储量 5% 的随机资源。此效果适用于手动购买和自动购买模式。\n\n已拥有",
    "Rapid Upgrade Protocols": "快速升级方案",
    "Cobblestone Compression": "鹅卵石压缩",
    "Dark Corner Shop": "黑暗角落商店",
    "Deep Forest Bounty": "森林深处赏金",
    "Ember Pact": "余烬公约",
    "Firewood Upcycling": "柴火升级改造",
    "Hardwood Barn": "硬木谷仓",
    "Improvised Shelter": "临时庇护所",
    "Increases Coal storage by 50, Iron Ore storage by 50, and Iron Ingots storage by 50": "使煤炭储存量增加 50，铁矿石储存量增加 50，铁锭储存量增加 50",
    "Increases Stone storage by 300 and gain 1 Stone every 3 seconds": "使石头储存量增加 300，并每 3 秒获得 1 块石头",
    "Increases Wood storage by 60 and Stone storage by 60 and gain 1 Wood every 4 seconds and gain 1 Stone every 4 seconds": "使木材储存量增加 60，石头储存量增加 60，并每 4 秒获得 1 份木材，每 4 秒获得 1 块石头",
    "Ironbark Accord": "铁皮木协议",
    "Stonewise Bargain": "石头讨价还价",
    "Sylvan Resonance": "森林共鸣",
    "Basic Adjustable Storage": "基础可调存储器",
    "Advanced Cobblestone Compression": "高级鹅卵石压缩",
    "Advanced Dark Forest Storage": "先进的黑暗森林存储",
    "Ancient Artifact Trading": "古代神器交易",
    "Ancient Wood Carving Art": "古代木雕艺术",
    "Artifact Coal Conversion": "神器煤炭转换",
    "Artifact Processing": "神器加工",
    "Artifact-Fueled Sawmill": "神器驱动锯木厂",
    "Basic Dark Forest Storage": "基础黑暗森林存储",
    "Charcoal Wood Conversion": "木炭木材转换",
    "Coal Mining Operations": "煤炭开采作业",
    "Coal Supply Route": "煤炭供应路线",
    "Coal-Fired Sawmill": "燃煤锯木厂",
    "Continuous Camp Improvements": "持续的营地改进",
    "Dark Forest Industrial Complex": "黑暗森林工业园区",
    "Dark Forest Roads": "黑暗森林道路",
    "Dark Forest Scouting Party": "黑暗森林侦察队",
    "Dark Forest Storage": "黑暗森林存储",
    "Dark Forest tile cost is 50% cheaper": "黑暗森林的存储成本降低 50%",
    "Dark Forest Warehousing": "黑暗森林仓储",
    "Dark Iron Foundry": "黑暗铁铸造厂",
    "Eldersaw Timber": "接骨木锯木材",
    "Eldertimber Gathering": "接骨木采集",
    "Emergency Wood Stockpile": "紧急木材储备",
    "Enhanced Coal Mining": "增强型煤炭开采",
    "Enhanced Ore Scavenging": "增强型矿石搜寻",
    "Entangling Roots": "缠绕的根系",
    "Establish Basic Coal Storage": "建立基本煤炭存储",
    "Establish Basic Iron Ore Storage": "建立基本铁矿石存储",
    "Every 3 seconds gain 5% of Wood maximum storage capacity worth of Wood.": "每 3 秒增加相当于最大木材存储容量 5% 的木材量。",
    "Every 4 seconds gain 250 Stone for every Dark Forge you currently own.": "当前拥有的每一个黑暗熔炉每4秒增加250石头。",
    "Forest Trade Network": "森林贸易网络",
    "Founder's Claim": "创始人声明",
    "Gain 10 Stone every 4 seconds, 10 Coal every 4 seconds, 10 Iron Ore every 4 seconds, and 1 Iron Ingots every 4 seconds": "每 4 秒获得 10 块石头、10 块煤炭、10 块铁矿石以及 1 个铁锭",
    "Gloom Wood Deals": "阴暗森林交易",
    "Hard Coal Combustion Plants": "硬煤燃烧厂",
    "Hardwood Chutes": "硬木斜坡",
    "Hidden Veinlets": "隐藏矿脉",
    "Improvised Coal Box": "简易煤箱",
    "Improvised Ore Box": "简易矿石箱",
    "Improvised Supply Camps": "简易补给营地",
    "Increases Stone storage by 250, Coal storage by 250, Iron Ore storage by 250, and Iron Ingots storage by 250": "使石头储存量增加 250，煤炭储存量增加 250，铁矿石储存量增加 250，铁锭储存量增加 250",
    "Increases storage capacity of all resources by 2 every second (caps at 1,080)": "所有资源的存储容量每秒增加 2（上限为 1080）",
    "Increases Wood storage by 25 per Dark Forest owned and Stone storage by 25 per Dark Forest owned": "拥有暗森林时，木材存储量增加 25，石头存储量增加 25",
    "Infernal Ironwood Forge": "地狱铁木锻造厂",
    "Iron Ingot Forge Basic": "铁锭锻造基础版",
    "Iron Ingot Forge Enhanced": "铁锭锻造增强版",
    "Iron Ore Scavenging": "铁矿石采集",
    "Iron Ore Stockpile": "铁矿石库存",
    "Iron-Enhanced Forestry": "铁增强型林业",
    "Ironsprout": "铁树苗",
    "Lumber Colossal Depot": "巨大木材仓库",
    "Obsidian Bark": "玄武岩树皮",
    "Open Cast Mining Operations": "露天采矿作业",
    "Pebble Collector": "砾石收集器",
    "Prayer Stands": "祈祷台",
    "Reforestation": "重新造林",
    "Scrap Wood Burning": "废木燃烧",
    "Shadow Artifact Sawmill": "阴影神器锯木厂",
    "Shadowwood Harvest": "影木收获",
    "Slash and Burn Farming": "砍伐与焚烧农业",
    "Spend up to 75% of available resources to auto-buy Dark Forest tiles.": "用可用资源的 75%自动购买暗森林方块。",
    "Start each run with 14 tiles already owned in the North, Northwest, West, Southwest, and South directions (up to distance 2 from start).": "每次开始时，在北、西北、西、西南和南方向（距离起点不超过 2 个单位）已有 14 块已拥有的暗森林方块。",
    "Start each run with a Dark Forge north of your starting position and a regular Forge south of your starting position.": "每次开始游戏时，先在起始位置以北放置一个“暗熔炉”，在起始位置以南放置一个“普通熔炉”。",
    "Start each run with all Quarry and Empty tiles east of your starting position already owned.": "每次开始游戏时，确保起始位置以东的所有“采石场”和“空地”都已被占领。",
    "Stone Stockpile": "石料储备库",
    "Stone Warehouse": "石料仓库",
    "Sylvan Proliferation": "森林繁衍",
    "Telluric Currents": "地壳电流",
    "Twilight Annexation": "暮光合并",
    "Ultimate Hardwood Barn": "终极硬木谷仓",
    "Umbral Crucible": "暗影熔炉",
    "Umbral Ironworks": "暗影铁厂",
    "Umbral Wood Firing": "暗影木料烘烤",
    "Underground Lumber Reserve": "地下木材储备库",
    "Add the current amount of Artifacts on hand as Wood and as Wood storage capacity every 3 seconds. The storage capacity bonus is capped at 1,000,000 Wood.": "每隔 3 秒，将手头现有的“神器”数量分别转换为“木材”以及“木材存储容量”。存储容量的加成上限为 1，000，000 木材。",
    "After purchasing a tile, automatically acquire any unowned tiles that are completely surrounded by your owned tiles (requires all 8 adjacent tiles). This cascades recursively.": "购买一块方块后，会自动获取任何完全被你拥有的方块所包围的未被拥有方块所包围的方块（需要所有 8 个相邻的方块）。这种效果会递归地持续下去。",
    "Each owned regular Forest reduces all tile costs by 1% multiplicatively. Maximum 50% cost reduction (reached at 50 Forests).": "每一块拥有的常规森林都会将所有方块的成本按 1% 的乘法因子降低。最多可降低 50% 的成本（达到 50 片森林时达到此效果）。",
    "Every tile you own produces +0.1 Artifacts per second on top of existing effects.": "你拥有的每一块方块都会在现有效果的基础上每秒额外产生 0.1 个“神器”。",
    "Every tile you own produces +0.1 Iron Ore per second on top of existing effects.": "你拥有的每一块方块都会在现有效果的基础上每秒额外产生 0.1 个铁矿石。",
    "Every tile you own produces +0.1 Stone per second on top of existing effects.": "你拥有的每一块方块都会在现有效果的基础上每秒额外产生 0.1 个石料。",
    "Start each run with all Forest tiles already in your possession.": "每次开始游戏时，所有的森林方块都已经在你的手中。",
    "Gain 200 Coal every 2 minutes. Increases Coal storage by 500.": "每 2 分钟获得 200 个煤炭。煤炭储存量增加 500。",
    "Artifact Ore Excavation": "神器矿石挖掘",
    "Basic Iron Smelting": "基础铁矿冶炼",
    "Iron Ore Warehouse": "铁矿石仓库",
    "Lumber Titan Warehouse": "木材泰坦仓库",
    "Advanced Artifact Processing": "高级物品处理",
    "Advanced Iron Ingot Production": "高级铁锭生产",
    "Advanced Iron Smelting": "高级炼铁",
    "All upgrades purchased!": "所有升级均已购买！",
    "Ancient Lumber Silo": "古代木材储藏室",
    "Artifact Vault Network": "文物库网络",
    "Auto-purchase Dark Forest every 2 seconds using 50% of available resources": "每隔 2 秒使用 50%的可用资源自动购买暗森林",
    "Basic Iron Ingot Production": "基础铁锭生产",
    "Coal Silo Complex": "煤仓复合体",
    "Congratulations! You've earned 5 Globes for completing Dark Forest for the 1st time!": "恭喜你! 第一次完成黑暗森林，你将获得5个球体！",
    "Dark Forest Auto-Buyer": "暗黑森林自动买家",
    "Elderwood Repository": "接骨木储存库",
    "Eternal Wood Archive": "永恒之木档案馆",
    "Expert Iron Smelting": "专家铁冶炼",
    "Frugal Conquest\n\nManual tile purchases have a chance to be free. Starts at 5% and increases by 5% each time it fails, resetting on success.\n\nCost: 3 Globes": "勤俭讨伐\n\n手动购买方块有概率免费。初始几率为 5%，每次失败时增加 5%，成功后重置。\n\n花费：3 球体",
    "Gain 10,000 Coal every 1 minute": "每 1 分钟获得 10，000 煤炭",
    "Gain 150 Coal every 3 seconds, 150 Iron Ore every 3 seconds, and 150 Iron Ingots every 3 seconds": "每 3 秒获得 150 煤炭、150 铁矿石和 150 铁锭",
    "Gain 50 Iron Ingots every 1 second and 50 Artifacts every 1 second": "每 1 秒获得 50 铁锭和 50 艺术品",
    "Grand Iron Smelting": "大炼铁",
    "Improved Iron Ingot Production": "改进的铁锭生产",
    "Improved Iron Smelting": "改进的铁冶炼",
    "Increases Coal storage by 50,000 and Iron Ingots storage by 50,000 and gain 3,000 Iron Ingots every 16 seconds": "将煤炭存储量增加 50，000，铁锭存储量增加 50，000，并每 16 秒获得 3，000 铁锭",
    "Industrial Iron Ingot Foundry": "工业铁锭铸造厂",
    "Industrial Storage and Smelting Complex": "工业储存和冶炼中心",
    "Infernal Coal Hearth": "炼狱煤炉",
    "Legendary Iron Smelting": "传说炼铁",
    "Lumber Mega-Depot": "木材超级仓库",
    "Master Iron Smelting": "炼铁大师",
    "Mega Coal Production Plant": "大型煤炭生产厂",
    "Mountain Passage Engineering": "山道工程",
    "Mountain tile cost is 50% cheaper": "山方块价格便宜50%",
    "Primeval Timber Vault": "原始木材宝库",
    "Shadow Masonry": "暗影砌筑",
    "Shadowsteel Artifact Foundry": "影钢神器铸造厂",
    "Titan Iron Artifact Forge": "泰坦铁艺术品熔炉",
    "Tri-Forged Smelting Union": "三锻熔炼联盟",
    "Turbo Iron Ingot Foundry": "涡轮铁锭铸造",
    "Ultimate Iron Smelting": "最终铁冶炼",
    "+1 passive step per second": "每秒增加 1 步的被动效果",
    "Alchemical Speed": "炼金速度",
    "Alchemy": "炼金术",
    "Alchetiles": "炼金块",
    "Alchetiles are crafted by accumulating steps over time.": "炼金块是通过不断积累的步骤制作而成的。",
    "Gain steps passively and by purchasing tiles manually or automatically.": "通过手动或自动购买方块来获得被动的步骤。",
    "Globe Infusion": "球体融合",
    "Grants 1 Globe": "提供 1 个球体",
    "Passive Rate": "被动速率",
    "Steps/Auto": "步骤/自动",
    "Steps/Manual": "步骤/手动",
    "Vials": "药瓶",
    "This Run": "当前轮次",
    "Total (All Runs)": "总计 (所有轮次)",
    "Rapid Upgrade Protocols\n\nEnhances the Auto-Upgrades Wisdom Grid feature. Reduces interval by 5x and purchases 2 upgrades per interval (10x total improvement). Requires the Auto-Upgrades Wisdom Grid node to have an effect.\n\nOwned": "快速升级协议\n\n增强了“自动升级智慧网格”功能。将间隔时间缩短 5 倍，并且每间隔可购买 2 次升级（总计提升 10 倍）。需要“自动升级智慧网格”节点生效。\n\n已拥有",
    "Congratulations! You've earned 4 Globes for completing Dark Forest for the 4th time!": "恭喜！第四次完成黑暗森林，你获得了4个金球奖！",
    "Converter Toggle\n\nAdds a master toggle to turn Forges and other converters on or off. Works on all maps with all tile types that convert resources.\n\nCost: 5 Globes": "转换器切换器\n\n添加一个主切换器，用于开启或关闭熔炉及其他转换器。适用于所有带有资源转换功能的地图及所有地形类型。\n\n花费：5 球体",
    "Frugal Conquest": "勤俭讨伐",
    "Improved Tile Queue": "改进的方块队列",
    "Improved Tile Queue\n\nIncreases tile queue capacity from 3 to 7.\n\nCost: 2 Globes": "改良的格子队列\n\n格子队列容量由3个增加到7个。\n\n消耗：2 球体",
    "Improved Tile Queue\n\nIncreases tile queue capacity from 3 to 7.\n\nOwned": "改良的格子队列\n\n格子队列容量由3个增加到7个。\n\n已拥有",
    "Increases tile queue capacity from 3 to 7.": "拥有队列容量从3增加到7。\n",
    "Manual tile purchases have a chance to be free. Starts at 5% and increases by 5% each time it fails, resetting on success.": "手动购买资源会有一定几率是免费的。从5%开始，每次失败增加5%，成功时重置。",
    "A dark obsidian forge that converts 10 Artifacts + 7 White Crystals into 1 Obsidian per second": "一个深色的黑曜石熔炉，每秒可将 10 个神器和 7 个白色晶体转化为 1 个黑曜石",
    "A luminous blue crystal formation that produces 0.2 Blue Crystals per second": "一个散发着蓝光的蓝色晶体结构，每秒可产生 0.2 个蓝色晶体",
    "A majestic snowy mountain peak - a breathtaking landmark with no practical benefit": "一座雄伟的雪峰——一处令人惊叹的地标，但没有实际用途",
    "A radiant white crystal formation that converts 20 Red + 20 Blue + 20 Green Crystals into 3 White Crystals per second": "一个闪耀的白色晶体结构，每秒可将 20 个红色、20 个蓝色和 20 个绿色晶体转化为 3 个白色晶体",
    "A vibrant red crystal formation that produces 0.1 Red Crystals per second": "一个充满活力的红色晶体结构，每秒产生 0.1 个红色晶体",
    "An archaeological excavation in the frozen wastes that converts 1 Green + 1 White Crystal into 1 Artifact per second": "在冰冻荒原进行的考古挖掘，每秒可将 1 个绿色和 1 个白色晶体转化为 1 个神器",
    "An emerald green crystal formation that produces 0.3 Green Crystals per second": "一个翠绿色的晶体结构，每秒产生 0.3 个绿色晶体",
    "Azure Excavation": "青色挖掘",
    "Blue Crystal Formation": "蓝色晶体形成",
    "Blue Crystal Formation tile cost is 20% cheaper": "蓝色水晶形成方块成本便宜20%",
    "Blue Crystals": "蓝色水晶",
    "Cobalt Infusion": "钴灌注",
    "Converts 1 Green Crystals + 1 White Crystals → 1 Artifacts/sec": "将 1 个绿色晶体和 1 个白色晶体转化为 1 个神器/秒",
    "Converts 10 Artifacts + 7 White Crystals → 1 Obsidian/sec": "将 10 个神器和 7 个白色晶体转化为 1 个黑曜石/秒",
    "Converts 21 Red Crystals + 21 Blue Crystals + 21 Green Crystals → 3 White Crystals/sec": "将 21 个红色晶体、21 个蓝色晶体和 21 个绿色晶体转化为 3 个白色晶体/秒",
    "Crimson Flow": "深红色流",
    "Crimson Fracturing": "深红色裂缝",
    "Crimson Resonance": "深红色共鸣",
    "Crystal Repository": "水晶存储库",
    "Dormant...": "休眠中...",
    "Frostbound Reserve": "冰冻储备",
    "Gain 1 Red Crystals every 3 seconds and increases Red Crystals storage by 100": "每3秒获得1个红色水晶，并增加100个红色水晶储存",
    "Gain 9 Red Crystals every 3 seconds, 9 Blue Crystals every 3 seconds, and 9 Green Crystals every 3 seconds": "每3秒获得9个红色水晶，9个蓝色水晶，9个绿色水晶",
    "Green Crystal Formation": "绿色晶体形成",
    "Green Crystals": "绿色水晶",
    "Increases Blue Crystals storage by 120 and gain 1 Blue Crystals every 10 seconds": "使蓝色水晶存储量增加 120，并每 10 秒获得 1 颗蓝色水晶",
    "Increases Blue Crystals storage by 80": "使蓝色水晶存储量增加 80",
    "Increases Red Crystals storage by 100": "使红色水晶存储量增加 100",
    "Obsidian Forge": "黑曜石熔炉",
    "Prismatic Convergence": "棱镜汇聚",
    "Red Crystal Formation": "红色晶体形成",
    "Red Crystal Formation tile cost is 20% cheaper": "红色水晶形成方块成本便宜20%",
    "Red Crystals": "红色水晶",
    "Ruby Satchel": "红宝石背包",
    "Sapphire Resonance": "蓝宝石共鸣",
    "Snowy Dig Site": "雪域挖掘点",
    "Snowy Mountain": "雪山",
    "White Crystal Formation": "白色晶体形成",
    "White Crystals": "白色水晶",
    "Frozen...": "冻结了...",
    "Sapphire Infusion": "蓝宝石灌注",
    "Deutsch": "德语",
    "Start each run with 21 tiles already owned in a crossroads pattern: 7 tiles to the west, 7 tiles to the east, and 7 tiles to the south of your starting position (all in straight lines).": "每次开始游戏时，先将 21 块方块以十字路口的布局方式放置好：向西 7 块、向东 7 块、向南 7 块（均沿直线排列）。",
    "Arboretum Tech": "植物园科技",
    "At the start of each run, 80% of Snowy Mountain tiles transform into Purple Crystal Formation tiles (tiles remain locked and must be purchased).": "每次运行开始时，80%的雪山地砖会转变为紫色水晶构造砖（这些砖块会保持锁定状态，必须购买才能使用）。",
    "Azure Refinery Tech": "湛蓝精炼厂科技",
    "Azure Skies": "湛蓝天空",
    "Biaural Peaks": "双耳山峰",
    "Black Abyss Tech": "黑色深渊科技",
    "Blue Push": "蓝色推进",
    "Crystal Crossroads": "水晶十字路口",
    "Elemental Equilibrium": "元素平衡",
    "Every 1.5 seconds, gain Green Crystals equal to the square root of the number of regular upgrades purchased in this run.": "每 1.5 秒，根据本次运行中购买的常规升级数量获得绿色水晶数量。",
    "Every 3 seconds, gain 1 Blue Crystal for each regular upgrade purchased in this run.": "每 3 秒，根据本次运行中购买的常规升级数量获得 1 个蓝色水晶。",
    "Every 5 seconds, gain Iron Ingots equal to the number of regular Upgrades purchased in this run.": "每 5 秒，获得与本次运行中购买的常规升级数量相同的铁锭。",
    "Every 5th upgrade purchased fully refills your Blue and Green Crystals to maximum storage.": "每购买第 5 个常规升级，将使您的蓝色和绿色水晶恢复到最大存储量。",
    "Every tile you own produces +0.13 Red Crystals per second on top of existing effects.": "您拥有的每块地砖都会在现有效果的基础上每秒额外产生 0.13 个红色水晶。",
    "Every tile you own produces +0.2 Wood per second on top of existing effects.": "您拥有的每块地砖还会在现有效果的基础上每秒额外产生 0.2 个木材。",
    "Geothermal Metamorphosis": "地热变形",
    "Green Grow": "绿色生长",
    "Lapidarium Tech": "宝石学科技",
    "Lowland Trade Routes": "低地商路",
    "Petrified Timber": "石化木材",
    "Rainbow Formations": "彩虹形成",
    "Red Rush": "红狂潮",
    "Reduces the cost of purchasing Red, Blue, Green, White, and Purple Crystal Formation tiles by 50%.": "将购买红色、蓝色、绿色、白色和紫色水晶构造砖的成本降低 50%。",
    "Reliquarium Tech": "宝库科技",
    "Ruby Breakthrough": "红宝石突破",
    "Spend up to 100% of available resources to auto-buy Green Crystal Formation tiles every 0.4 seconds.": "每 0.4 秒使用最多可用资源自动购买绿色水晶构造砖。",
    "Spend up to 80% of available resources to auto-buy Red Crystal Formation tiles every 0.4 seconds.": "每 0.4 秒自动购买最多 80% 可用资源的红色水晶阵列方块。",
    "Spend up to 90% of available resources to auto-buy Blue Crystal Formation tiles every 0.4 seconds.": "每 0.4 秒自动购买最多 90% 可用资源的蓝色水晶阵列方块。",
    "Unlocks additional cheap early- and mid-game Upgrades that improve Blue Crystals income and storage.": "解锁了早期和中期游戏中的更多廉价升级，这些升级能提高蓝色水晶的产出和存储能力。",
    "Unlocks additional Upgrades that cost mostly Artifacts and grant various bonuses across all aspects of the game.": "解锁了更多主要由神器构成的升级，能在游戏的所有方面提供各种加成。",
    "Unlocks additional Upgrades that require Stone which increase Stone income and storage.": "解锁了更多需要石料的升级，能增加石料的产出和存储量。",
    "Unlocks advanced arboreal technology upgrades in the Upgrade shop, allowing you to increase wood storage capacity and gain wood over time using crystals.": "在升级商店中解锁了先进的树木技术升级，使您能够增加木材存储容量，并通过水晶逐渐获取木材。",
    "Unlocks Obsidian-based late-game upgrades that interact with all other resources.": "解锁了与所有其他资源相互作用的基于玄武岩的后期游戏升级。",
    "Verdant Roots": "绿叶根系",
    "Crimson Iron Vault": "绯红铁宝库",
    "Obsidian Ember Cache": "黑曜石火种库",
    "Ruby Resonance": "红宝石共鸣",
    "Azure Tide": "蓝潮",
    "Azure Tide IX": "蓝潮 IX",
    "Blue Crystal Formation tile cost is 50% cheaper": "蓝色水晶形成瓷砖成本便宜50%",
    "Boreal Resonance": "北境共鸣",
    "Crimson Cascade": "猩红瀑布",
    "Dual Geode Integration": "双晶石整合",
    "Emerald Pulse": "翡翠脉冲",
    "Emerald Tide": "翡翠潮",
    "Green Crystal Formation tile cost is 25% cheaper": "绿色水晶阵列的建造费用降低 25%",
    "Increases Blue Crystals storage by 6 per Blue Crystal Formation owned": "增加已拥有的蓝色水晶的存储量 6 个",
    "Increases Green Crystals storage by 9 per Red Crystal Formation owned and Green Crystals storage by 9 per Blue Crystal Formation owned": "增加已拥有的红色水晶阵列的存储量 9 个以及已拥有的蓝色水晶阵列的存储量 9 个",
    "Increases Red Crystals storage by 150 and Blue Crystals storage by 150": "增加红色水晶的存储量 150 个以及蓝色水晶的存储量 150 个",
    "Increases Red Crystals storage by 3 per Red Crystal Formation owned": "增加红色水晶的存储量 3 个（每拥有一个红色水晶阵列）",
    "Jade Synergy": "翡翠协同",
    "Obsidian Frost Vault": "玄武岩冰窖",
    "Obsidian Grove Reservoir": "玄武岩丛林蓄水池",
    "Ruby Coffer": "红宝石宝箱",
    "Ruby Geode Storage": "红宝石晶石存储",
    "Sapphire Extraction": "蓝宝石提取",
    "Sapphire Geode Storage": "蓝宝石晶石存储",
    "Sapphire Vein Resonance": "蓝宝石矿脉共鸣",
    "Verdant Resonance": "翠绿共鸣",
    "Artifact Emerald Resonance": "神器翡翠共鸣",
    "Green Crystal Formation tile cost is 50% cheaper": "绿色水晶构造板块的制作成本降低 50%",
    "Increases Obsidian storage by 1 every 1 second (caps at +50 total)": "每秒增加 1 点黑曜石存储量（总量上限为 +50）",
    "Jade Compression": "翡翠压缩玄武岩",
    "Obsidian": "黑曜石",
    "Obsidian Infusion": "黑曜石灌注",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Impressum & Datenschutzerklärung": "Impressum & Datenschutzerklärung",
    "idlesquares@gmail.com": "idlesquares@gmail.com",
    "BlacKcuD": "BlacKcuD",
    "Welgaia, Tschi": "Welgaia, Tschi",
    "N/A": "N/A",
    "var:": "变量:",
    "AP": "成就点数",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "???": "???",
    "•": "•",
    "−": "−",
    "⊞": "⊞",
    "⊡": "⊡",
    "🔒": "🔒",
    "→": "→",
    "✕": "✕",
    "×": "×",
    "▼": "▼",
    "⚙": "⚙",
    "ℹ": "ℹ",
    "✅": "✅",
    "🏘️": "🏘️",
    "⚡": "⚡",
    "🏆": "🏆",
    "📖": "📖",
    "📜": "📜",
    "☕": "☕",
    "⬆️": "⬆️",
    "✓": "✓",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "@": "@",
    "^": "^",
    "&": "&",
    "%": "%",
    "--": "--",
    "=": "=",
    "?": "?",
    "!": "!",
    "$": "$",
    "#": "#",
    "/": "/",
    "]": "]",
    "[": "[",
    "+": "+",
    ".": ".",
    "…": "…",
    ":": ":",
    "-": "-",
    "|": "|",
    "(": "(",
    ")": ")",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Gityx游戏': 'Gityx游戏',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    'a': 'a',
    'b': 'b',
    'c': 'c',
    'd': 'd',
    'e': 'e',
    'f': 'f',
    'g': 'g',
    'h': 'h',
    'i': 'i',
    'j': 'j',
    'k': 'k',
    'l': 'l',
    'm': 'm',
    'n': 'n',
    'o': 'o',
    'p': 'p',
    'q': 'q',
    'r': 'r',
    's': 's',
    't': 't',
    'u': 'u',
    'v': 'v',
    'w': 'w',
    'x': 'x',
    'y': 'y',
    'z': 'z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Animations: ": "动画: ",
    "Current Endgame: ": "当前终局: ",
    "Space Background: ": "太空背景: ",
    "Tile Cost: ": "方块成本: ",
    "Your current Tile Cost Multiplier is ": "你当前的方块成本乘数是 ",
    "Only available on: ": "仅可用于: ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    " (Iron Ore)": " (铁矿石)",
    " (Stone)": " (石头)",
    " (Wood)": " (木头)",
    " (Coal)": " (煤)",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)$/,
    /^×([\d\.]+)$/,
    /^x([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^\(([\d\.]+), ([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^\+([\d\.]+)\%$/,
    /^\-([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^\(([\d\.]+),([\d\.]+)\)$/,
    /^\(\-([\d\.]+),([\d\.]+)\)$/,
    /^\(\-([\d\.]+),\-([\d\.]+)\)$/,
    /^\(([\d\.]+),\-([\d\.]+)\)$/,
    /^每(.+)$/,
    /^提高(.+)$/,
    /^基础(.+)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+) ([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.]+)\/([\d\.]+) ([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+) \/ ([\d\.]+)(.+)$/,
    /^([\d\.]+)(.+) \/ ([\d\.]+)(.+)$/,
    /^\[([\d\.]+):([\d\.]+):([\d\.]+)\]$/,
    /^([\d\.]+)K$/,
    /^\+([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^×([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^Spend (.+) total Globes on World Tree nodes.$/, '在“世界树”节点上总共花费 $1 球体。'],
    [/^Converts (.+) Coal \+ (.+) Iron Ore → (.+) Iron Ingots\/sec$/, '转化 $1 煤 + $2 铁矿石 → $3 铁锭/秒'],
    [/^Auto-purchase Mountain every (.+) seconds using (.+) of available resources$/, '使用 $2 可用资源，每 $1 秒自动购买一次高山'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
    [/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^([\d\.]+)\/s$/, '$1\/秒'],
    [/^\(\+([\d\.]+)\/s\)$/, '(+$1\/秒)'],
    [/^([\d\.,]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^\+([\d\.]+) elves$/, '+$1 精灵'],
    [/^\+([\d\.]+)\% elves$/, '+$1% 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)h ([\d\.]+)m$/, '$1小时 $2分'],
    [/^([\d\.]+)m ([\d\.]+)s$/, '$1分钟 $2秒'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^\+([\d\.,]+) Bonus!$/, '+$1 加成!'],
    [/^\+([\d\.,]+) elves$/, '+$1 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) Degrees Celsius$/, '$1 摄氏度'],
    [/^Unlocks after owning ([\d\.,]+) more tiles$/, '再拥有 $1 方块之后解锁'],
    [/^Unlocks after owning ([\d\.,]+) more tile$/, '再拥有 $1 方块之后解锁'],
    [/^Produces ([\d\.,]+) Red Crystals\/sec$/, '生产 $1 红水晶/秒'],
    [/^Produces ([\d\.,]+) Blue Crystals\/sec$/, '生产 $1 蓝水晶/秒'],
    [/^Produces ([\d\.,]+) Green Crystals\/sec$/, '生产 $1 绿水晶/秒'],
    [/^Produces ([\d\.,]+) Coal\/sec$/, '生产 $1 煤/秒'],
    [/^Produces ([\d\.,]+) Iron Ore\/sec$/, '生产 $1 铁矿石/秒'],
    [/^Produces ([\d\.,]+) Wood\/sec$/, '生产 $1 木头/秒'],
    [/^Produces ([\d\.,]+) Stone\/sec$/, '生产 $1 石头/秒'],
    [/^Upgrades \(([\d\.,]+)\)$/, '升级 ($1)'],
    [/^Have ([\d\.,]+) Artifacts on hand.$/, '手中持有 $1 神器.'],
    [/^Have ([\d\.,]+) Iron Ingots on hand.$/, '手中持有 $1 铁锭.'],
    [/^Have ([\d\.,]+) Stone on hand.$/, '手中持有 $1 石头.'],
    [/^Have ([\d\.,]+) Wood on hand.$/, '手中持有 $1 木头.'],
    [/^Have ([\d\.,]+) Red Crystals on hand$/, '手中持有 $1 红水晶'],
    [/^Have ([\d\.,]+) Stone on hand on Crystal Peak$/, '手中持有 $1 石头 在水晶山'],
    [/^Have ([\d\.,]+) Wood on hand at once$/, '手中一次性持有 $1 木头.'],
    [/^Have ([\d\.,]+) Stone on hand at once$/, '手中一次性持有 $1 石头.'],
    [/^Have ([\d\.,]+) Coal on hand.$/, '手中持有 $1 煤.'],
    [/^Have ([\d\.,]+) Iron Ingots storage capacity on Crystal Peak$/, '拥有 $1 铁锭 存储容量 在水晶山'],
    [/^Have ([\d\.,]+) Obsidian storage capacity$/, '拥有 $1 黑曜石 存储容量'],
    [/^Have ([\d\.,]+) Iron Ingot storage capacity on Crystal Peak$/, '拥有 $1 铁锭 存储容量 在水晶山'],
    [/^Have a Coal storage capacity of ([\d\.,]+)$/, '拥有 $1 煤 存储容量'],
    [/^Have a Stone storage capacity of ([\d\.,]+)$/, '拥有 $1 石头 存储容量'],
    [/^Have a Wood storage capacity of ([\d\.,]+)$/, '拥有 $1 木头 存储容量'],
    [/^Have an Iron Ingot storage capacity of ([\d\.,]+)$/, '拥有 $1 铁锭 存储容量'],
    [/^Have an Iron Ore storage capacity of ([\d\.,]+)$/, '拥有 $1 铁矿石 存储容量'],
    [/^Purchase ([\d\.,]+) Dark Forest Upgrades.$/, '购买 $1 黑暗森林升级。'],
    [/^Purchase ([\d\.,]+) Upgrades in a single run.$/, '在单轮游戏中购买 $1 升级。'],
    [/^Purchase ([\d\.,]+) upgrades in a single run$/, '在单轮游戏中购买 $1 升级'],
    [/^Purchase ([\d\.,]+) upgrades total across all runs$/, '在所有游戏轮次中总计购买 $1 升级'],
    [/^Own ([\d\.,]+) Quarries$/, '拥有 $1 采石场'],
    [/^Own ([\d\.,]+) Empty Lands$/, '拥有 $1 空地'],
    [/^Own ([\d\.,]+) Coal Deposits$/, '拥有 $1 煤矿床'],
    [/^Own ([\d\.,]+) Forges$/, '拥有 $1 锻炉'],
    [/^Own ([\d\.,]+) Forests$/, '拥有 $1 森林'],
    [/^Own ([\d\.,]+) Dark Forests.$/, '拥有 $1 黑暗森林.'],
    [/^Own ([\d\.,]+) Empty Land on Dark Forests.$/, '在黑暗森林拥有 $1 空地.'],
    [/^Own ([\d\.,]+) Empty Land on Dark Forest.$/, '在黑暗森林拥有 $1 空地.'],
    [/^Own ([\d\.,]+) Iron Mines$/, '拥有 $1 铁矿'],
    [/^Own ([\d\.,]+) tiles$/, '拥有 $1 方块'],
    [/^Own ([\d\.,]+) tiles.$/, '拥有 $1 方块.'],
    [/^Own ([\d\.,]+) Rivers on Riverside$/, '在河畔拥有 $1 河流'],
    [/^Own ([\d\.,]+) Rivers on Riverside.$/, '在河畔拥有 $1 河流.'],
    [/^Own ([\d\.,]+) Riverbanks on Riverside$/, '在河畔拥有 $1 河堤'],
    [/^Own ([\d\.,]+) tiles on Meadows.$/, '在草地拥有 $1 方块.'],
    [/^Own ([\d\.,]+) tiles on Crystal Peak.$/, '在水晶山拥有 $1 方块.'],
    [/^Own ([\d\.,]+) tiles on Crystal Peak$/, '在水晶山拥有 $1 方块'],
    [/^Own ([\d\.,]+) Dig Sites.$/, '拥有 $1 挖掘点.'],
    [/^Own ([\d\.,]+) tiles total.$/, '总计拥有 $1 方块.'],
    [/^Own ([\d\.,]+) Mountains.$/, '拥有 $1 高山.'],
    [/^Own ([\d\.,]+) Empty Lands$/, '拥有 $1 空地'],
    [/^Own ([\d\.,]+) tiles total$/, '总计拥有 $1 方块'],
    [/^Gain ([\d\.,]+) Blue Crystals every ([\d\.,]+) seconds$/, '每 $2 秒获得 $1 蓝水晶'],
    [/^Gain ([\d\.,]+) Green Crystals every ([\d\.,]+) seconds$/, '每 $2 秒获得 $1 绿水晶'],
    [/^Gain ([\d\.,]+) White Crystals every ([\d\.,]+) seconds$/, '每 $2 秒获得 $1 白水晶'],
    [/^Gain ([\d\.,]+) Red Crystals every ([\d\.,]+) seconds$/, '每 $2 秒获得 $1 红水晶'],
    [/^Gain ([\d\.,]+) Wood every ([\d\.,]+) seconds$/, '每 $2 秒获得 $1 木头'],
    [/^Gain ([\d\.,]+) Iron Ore every ([\d\.,]+) seconds$/, '每 $2 秒获得 $1 铁矿石'],
    [/^Gain ([\d\.,]+) Iron Ore every ([\d\.,]+) seconds and ([\d\.,]+) Iron Ingots every ([\d\.,]+) seconds$/, '每 $2 秒获得 $1 铁矿石，并且每 $4 秒获得 $3 铁锭'],
    [/^Gain ([\d\.,]+) Wood every ([\d\.,]+) second and ([\d\.,]+) Stone every ([\d\.,]+) second$/, '每 $2 秒获得 $1 木头，并且每 $4 秒获得 $3 石头'],
    [/^Gain ([\d\.,]+) Iron Ingots every ([\d\.,]+) seconds$/, '每 $2 秒获得 $1 铁锭'],
    [/^Gain ([\d\.,]+) Iron Ingots every ([\d\.,]+) minute$/, '每 $2 分钟获得 $1 铁锭'],
    [/^Gain ([\d\.,]+) Artifacts every ([\d\.,]+) seconds$/, '每 $2 秒获得 $1 神器'],
    [/^Gain ([\d\.,]+) Artifacts every ([\d\.,]+) second$/, '每 $2 秒获得 $1 神器'],
    [/^Gain ([\d\.,]+) Wood every ([\d\.,]+) second$/, '每 $2 秒获得 $1 木头'],
    [/^Gain ([\d\.,]+) Coal every ([\d\.,]+) seconds$/, '每 $2 秒获得 $1 煤'],
    [/^Gain ([\d\.,]+) Stone every ([\d\.,]+) seconds$/, '每 $2 秒获得 $1 石头'],
    [/^Gain ([\d\.,]+) Wood every ([\d\.,]+) seconds$/, '每 $2 秒获得 $1 木头'],
    [/^Gain ([\d\.,]+) Coal every ([\d\.,]+) seconds and increases Wood storage by ([\d\.,]+) and increases Coal storage by ([\d\.,]+)$/, '每 $2 秒获得 $1 煤，并且使木头储存量增加 $3，同时使煤炭储存量也增加 $4。'],
    [/^Increases Coal storage by ([\d\.,]+) every ([\d\.,]+) second \(caps at \+([\d\.,]+) total\)$/, '提高 煤 存储量 $1 每 $2 秒 (总上限是 +$3)'],
    [/^Increases Stone storage by ([\d\.,]+) every ([\d\.,]+) second \(caps at \+([\d\.,]+) total\)$/, '提高 石头 存储量 $1 每 $2 秒 (总上限是 +$3)'],
    [/^Increases Stone storage by ([\d\.,]+) and gain ([\d\.,]+) Stone every ([\d\.,]+) seconds$/, '提高 石头 存储量 $1 和 $2 石头 每 $3 秒'],
    [/^Increases Iron Ore storage by ([\d\.,]+) every ([\d\.,]+) second \(caps at \+([\d\.,]+) total\)$/, '提高 铁矿石 存储量 $1 每 $2 秒 (总上限是 +$3)'],
    [/^Increases Wood storage by ([\d\.,]+) every ([\d\.,]+) second \(caps at \+([\d\.,]+) total\)$/, '提高 木头 存储量 $1 每 $2 秒 (总上限是 +$3)'],
    [/^Increases Coal storage by ([\d\.,]+)$/, '提高煤存储量 $1'],
    [/^Increases Coal storage by ([\d\.,]+), Iron Ingots storage by ([\d\.,]+), and Artifacts storage by ([\d\.,]+)$/, '提高煤存储量 $1，铁锭存储 $2，和神器存储 $3'],
    [/^Increases Coal storage by ([\d\.,]+), Stone storage by ([\d\.,]+), and Coal storage by ([\d\.,]+)$/, '提高煤存储量 $1，石头存储 $2，和煤存储 $3'],
    [/^Increases Wood storage by ([\d\.,]+), Stone storage by ([\d\.,]+), and Coal storage by ([\d\.,]+)$/, '提高木头存储量 $1，石头存储 $2，和煤存储 $3'],
    [/^Increases Wood storage by ([\d\.,]+)$/, '提高木头存储量 $1'],
    [/^Increases Red Crystals storage by ([\d\.,]+)$/, '提高 红水晶 存储量 $1'],
    [/^Increases Green Crystals storage by ([\d\.,]+)$/, '提高 绿水晶 存储量 $1'],
    [/^Increases White Crystals storage by ([\d\.,]+)$/, '提高 白水晶 存储量 $1'],
    [/^Increases Blue Crystals storage by ([\d\.,]+)$/, '提高 蓝水晶 存储量 $1'],
    [/^Increases Artifacts storage by ([\d\.,]+)$/, '提高 神器 存储量 $1'],
    [/^Increases Iron Ore storage by ([\d\.,]+)$/, '提高 铁矿石 存储量 $1'],
    [/^Increases Iron Ingots storage by ([\d\.,]+)$/, '提高 铁锭 存储量 $1'],
    [/^Increases Iron Ingots storage by ([\d\.,]+) and Artifacts storage by ([\d\.,]+)$/, '提高铁锭存储量 $1 以及 神器存储量 $2'],
    [/^Increases Blue Crystals storage by ([\d\.,]+) and gain ([\d\.,]+) Blue Crystals every ([\d\.,]+) seconds$/, '提高蓝水晶存储量 $1 以及 获得 $2 蓝水晶 每 $3 秒'],
    [/^Increases Wood storage by ([\d\.,]+) and Coal storage by ([\d\.,]+)$/, '提高木头存储量 $1 以及 煤存储量 $2'],
    [/^Increases Wood storage by ([\d\.,]+) and Stone storage by ([\d\.,]+)$/, '提高木头存储量 $1 以及 石头存储量 $2'],
    [/^Increases Wood storage by ([\d\.,]+) per Empty Land owned$/, '拥有的每块空地，都提高木头存储量 $1'],
    [/^Increases Artifacts storage by ([\d\.,]+) per Empty Land owned$/, '拥有的每块空地，都提高神器存储量 $1'],
    [/^Increases Stone storage by ([\d\.,]+)$/, '提高石头存储量 $1'],
    [/^Increases Stone storage by ([\d\.,]+), Coal storage by ([\d\.,]+), and Iron Ore storage by ([\d\.,]+)$/, '提高石头存储量 $1, 煤存储量 $2, 以及铁矿石存储量 $3'],
    [/^Extra Wisdom Points in ([\d\.,]+) tiles$/, '获得额外的智慧点还需 5 方块'],
    [/^Last save: ([\d\.,]+) seconds ago$/, '最近保存: $1 秒前'],
    [/^and ([\d\.,]+) rows completed$/, '以及 $1 行已完成'],
    [/^Row ([\d\.,]+)$/, '第 $1 行'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^You will earn ([\d\.,]+) Wisdom Points.$/, '您将获得 $1 智慧点数。'],
    [/^Spend ([\d\.,]+) more Globes$/, '再花费 $1 个球体'],
    [/^([\d\.,]+) of ([\d\.,]+) Achievements earned$/, '$1 \/ $2 成就已获得'],
    [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);