/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Join the Discord!": "加入 Discord!",
    "Fix export button and save": "修复导出按钮和保存",
    "ENABLED": "启用",
    "Export to file": "导出为文件",
    "Import clipboard": "从剪贴板导入",
    "Import file": "从文件导入",
    "DISABLED": "禁用",
    "Experience": "经验值",
    "Cancel": "取消",
    "/s": "/秒",
    "% Tile Cost": "% 方块成本",
    "About": "关于",
    "← Previous": "← 上一条",
    "by BlacKcuD": "作者 BlacKcuD",
    "An Incremental Grid-Based Strategy Game": "一款基于网格的渐进式策略游戏",
    "Did you know?": "你知道吗？",
    "Each square type generates different resources.": "每种方块类型都会产生不同的资源。",
    "Idle-Squares": "方块放置",
    "IDLE-SQUARES": "方块放置",
    "Loading sprites...": "正在加载贴图...",
    "Meadows": "草地",
    "Next →": "下一条 →",
    "Resources": "资源",
    "Skip Tutorial": "跳过教程",
    "Wisdom": "智慧",
    "Stone": "石头",
    "Wood": "木头",
    "Your goal is to conquer the entire map by purchasing all tiles. Once complete, advance to the next map and repeat.": "你的目标是通过购买所有方块来征服整个地图。完成之后，就前往下一个地图并重复此过程。",
    "Welcome to Idle-Squares!": "欢迎来到 方块放置!",
    "Upgrades": "升级",
    "Unlocking Tiles": "解锁方块",
    "Wisdom Grid Upgrades": "智慧网格升级",
    "The Grid": "网格",
    "Progress far enough and you'll unlock the Wisdom Grid—a powerful upgrade system that makes every future run stronger. Resetting to claim your Wisdom Points is a milestone, not a setback. Build your permanent power and conquer faster each time!": "继续前进到一定程度，你就能解锁“智慧网格”——这是一个强大的升级系统，能让你每次的后续游戏都变得更加强大。重新开始以获取你的“智慧点数”是一个重要的里程碑，而非挫折。积累你的永久力量，每次都能更快地取得胜利！",
    "This is your territory. You start with one unlocked tile. Expand by purchasing adjacent tiles. Tile costs increase significantly the further you expand and the more you own—strategic planning is essential.": "这是你的领地。你一开始拥有一个未锁定的方块。通过购买相邻的方块来扩大领地范围。随着扩张范围的扩大以及拥有的方块数量的增加，方块的成本也会大幅提高——因此，进行合理的规划至关重要。",
    "Crafting recipes unlock as you progress through the game.": "随着游戏进程的推进，您会解锁制作配方。",
    "Purchase adjacent tiles to expand your territory and explore the map. Each tile costs resources based on its distance from your starting tile and your current progress.": "购买相邻的方块可以扩大您的领地并探索地图。每个方块的成本取决于其与您起始方块的距离以及您当前的进展程度，其所需资源量会有所不同。",
    "Unknown Territory": "未知领土",
    "Keyboard shortcuts available - press ? in the top right to see them.": "键盘快捷键可用——在右上角按“？”键即可查看。",
    "Forest": "森林",
    "Iron Mine": "铁矿",
    "Initializing game...": "正在初始化游戏...",
    "Quarry": "采石场",
    "Tent": "帐篷",
    "Coal Deposit": "煤矿床",
    "A coal deposit that produces Coal": "产出煤炭的煤矿",
    "A dense forest that produces Wood": "一片茂密的森林，能产出木头",
    "A stone quarry that produces Stone": "可以生产石头的采石场",
    "An iron mine that produces Iron Ore": "一个铁矿，能产出铁矿石",
    "Hover over items to see more information about them.": "点击物品可查看更多相关信息。",
    "Unlock adjacent tiles first": "首先解锁相邻的方块",
    "Your humble beginnings": "你的卑微起点",
    "Achievement Unlocked!": "成就已解锁!",
    "Yay!": "耶!",
    "Nice Tutorial": "精彩的教程",
    "Play on Meadows for 10 minutes.": "在草地上玩 10 分钟。",
    "Shrine": "神殿",
    "Empty Land": "空地",
    "Coal": "煤",
    "A sacred shrine surrounded by mountains that increases all resource gains by 10%": "一座群山环绕的神殿，使所有资源收益提高10%",
    "An empty plot of land that serves no purpose, yet": "一块空旷的土地，毫无用途可言，",
    "Unlocking new squares opens up more resources to generate.": "但解锁新的区域后，会带来更多可生成的资源。",
    "Unlock Upgrades": "解锁升级",
    "An empty plot of land that serves no purpose, yet": "一块没有任何用途的空地",
    "Apprentice Tree Cultivation": "学徒树栽培",
    "Chop Chop!": "砍砍!",
    "Clever Stone Stacking": "巧妙的石头堆砌",
    "Coal Warehousing": "煤炭储存",
    "Continuous Improvements": "持续改进",
    "Diggy Diggy Hole": "挖，挖，挖",
    "Empty Land tile cost is 50% cheaper": "空地方块成本降低50%",
    "Forest tile cost is 20% cheaper and increases Wood storage by 200": "森林方块成本降低20%，木头储存量增加200",
    "Increases Coal storage by 50 per Empty Land owned": "每拥有一个空地，煤炭储存量增加 50",
    "Increases Iron Ore storage by 50 per Empty Land owned": "每拥有一个空地，铁矿石储存量增加 50",
    "Increases Stone storage by 50 per Empty Land owned": "每拥有一个空地，石头储存量增加 50",
    "Increases storage capacity of all resources by 1 every second (caps at 10,000)": "所有资源的存储容量每秒增加 1（上限为 10，000）",
    "Iron Ore Warehousing": "铁矿石储存",
    "It`s bigger on the inside": "内部更大",
    "Log Piles": "木材堆",
    "Lumber Warehousing": "木头仓库",
    "Nothing but space": "一片空旷之地",
    "Pile On": "堆积起来",
    "Protected Forests": "森林保护区",
    "Stone Warehousing": "石头仓库",
    "Weatherproof Storage Area": "防风雨储存区",
    "You can save your game at any time with Ctrl+S!": "您可以在任何时候通过按 Ctrl+S 保存游戏！",
    "But what does it do?": "但它究竟有什么作用呢？",
    "Woodstock": "木头存储",
    "Forge": "锻炉",
    "Fuel for the Fire": "生火燃料",
    "Iron Ore": "铁矿石",
    "Riverside": "河畔",
    "Dark Forest": "黑暗森林",
    "Crystal Peak": "水晶山",
    "Own a Shrine": "拥有一个神殿",
    "Own a Dark Forge.": "拥有一个黑暗锻炉.",
    "Own a Dark Forge on Riverside": "在河畔拥有一个黑暗锻炉",
    "Own your first Forge": "拥有你的第一个锻炉",
    "Buy 25 Upgrades in one run": "在单轮游戏中购买 25 升级",
    "A blazing hot forge that refines 1 Coal + 1 Iron Ore into 1 Iron Ingot every second": "一个炽热的熔炉，每秒将1个煤+ 1个铁矿石提炼成1个铁锭",
    "A majestic mountain peak - an expensive landmark with no practical benefit, yet": "一座雄伟的山峰——这是一座昂贵的地标性建筑，但毫无实际用途。",
    "Achievement Points": "成就点数",
    "All tiles become cheaper to purchase based on your total Achievement Points.": "根据您的总成就点数，所有地块的购买价格都会降低。",
    "Almost There": "差不多了",
    "Are we there yet?": "我们到那儿了吗？",
    "Big, Pink, and Useless": "巨大、粉红且毫无用处",
    "But what does it do?": "但它有什么作用呢？",
    "Can never have enough": "永远都嫌不够",
    "Capture all Shrines on Riverside": "占领河滨的所有神殿",
    "Coal Baron": "煤炭大亨",
    "Coal is the true endgame": "煤炭才是真正的终局",
    "Come to the Dark Side": "加入黑暗阵营",
    "Complete rows of 4 achievements to earn +5 bonus points per row!": "完成4行成就，每行获得+5奖励点！",
    "Crystal Breakthrough": "水晶突破",
    "Crystal Crown": "水晶王冠",
    "Crystal Peak Completionist": "水晶巅峰完成者",
    "Deuteranopia": "色盲",
    "Diggy Diggy Ore": "挖掘矿石",
    "Discover a Dig Site": "发现一个挖掘地点",
    "Each Achievement is worth 1 Achievement Point.": "每个成就值 1 个成就点。",
    "Each completed row is worth 5 bonus Achievement Points.": "每完成一行可获得 5 个奖励成就点。",
    "Emerald Empire": "翡翠帝国",
    "Fields of Green": "绿色田野",
    "Forest for the trees": "为树木而建的森林",
    "Full Metal Jacket": "全金属外壳",
    "Gonna upgrade them all": "要将它们全部升级",
    "Hall of the Mountain King": "山之国王的殿堂",
    "Happy Little Trees": "快乐的小树",
    "Have coal max storage capacity of 10,000 in Dark Forest.": "在黑暗森林中拥有最大的煤炭储存量10000。",
    "Hide completed rows": "隐藏已完成的行",
    "How many are there?": "有多少个？",
    "How much weighs the Earth?": "地球有多重？",
    "I got 99 Tiles": "我获得了99格",
    "I really like Upgrades": "我真的很喜欢升级",
    "I think we have enough fire wood now": "我想我们现在有足够的木柴了",
    "Indiana Jones is in every Game": "印第安纳·琼斯出现在每一款游戏中",
    "Industrial Revolution": "工业革命",
    "Industrialization 2.0": "工业化2.0",
    "Keep Piling em Up": "继续堆积",
    "Let's make it an even number": "让我们把它变成偶数",
    "Light-flooded Clearing": "光线充足的空地",
    "Meadows Victory": "草地胜利",
    "Melt it all down": "融化一切",
    "More Wisdom Points": "更多的智慧点数",
    "Mount Everest": "珠穆朗玛峰",
    "Mountain": "山",
    "My favourite Tree": "我最喜欢的树",
    "Not this Again": "别再这样了",
    "On the Beach": "在海滩上",
    "Own 1 Green Crystal Formation on Crystal Peak": "拥有水晶山上的 1 个绿色晶体结构",
    "Own 1 Mountain on Dark Forest.": "在黑暗森林拥有一座山。",
    "Own 10 regular Forges on Dark Forest.": "在暗森林中拥有 10 座常规熔炉",
    "Own 100 Blue Crystal Formations on Crystal Peak": "在水晶山上拥有 100 个蓝色晶体结构",
    "Own 100 Green Crystal Formations on Crystal Peak": "在水晶山上拥有 100 个绿色晶体结构",
    "Own 100 Red Crystal Formations on Crystal Peak": "在水晶山上拥有 100 个红色晶体结构",
    "Own 3 Purple Crystal Formations on Crystal Peak": "在水晶山上拥有 3 个紫色晶体结构",
    "Own 33 White Crystal Formations on Crystal Peak": "在水晶山上拥有 33 个白色晶体结构",
    "Picky Customer": "挑剔的顾客",
    "Play on Dark Forest for 10 minutes.": "在黑暗森林玩10分钟。",
    "Praying Man": "祈祷者",
    "Pulsing Purple Power": "搏动的紫色之力",
    "Purchase all Upgrades in Crystal Peak.": "购买水晶山上的所有升级物品。",
    "Purchase an Obsidian Forge on Crystal Peak": "在水晶山上购买一座黑曜石熔炉",
    "Ready for Endgame?": "准备好终局了吗？",
    "Ready to Melt": "准备熔炼",
    "Red-Fifteen": "红十五",
    "Ruby Fields": "红宝石原野",
    "Sacred Place": "神圣之地",
    "Sapphire Sea": "蓝宝石海洋",
    "Save the Rainforests!": "拯救雨林！",
    "Scaling Up Production": "扩大生产规模",
    "Shrine Shenanigans": "神殿闹剧",
    "Smell of Napalm": "汽油弹的气味",
    "Surround a Crystal Monument without owning it": "在不拥有的情况下包围水晶纪念碑",
    "Surround a Forest without owning it": "在不拥有的情况下包围森林",
    "Surround a Mountain without owning it": "在不拥有的情况下包围山脉",
    "Surround a Shrine without owning it on Crystal Peak": "在水晶山环绕一个神殿而不拥有它",
    "Surround an Empty Land without owning it": "不拥有的情况下包围一片空地",
    "Ten Stones on a Mountain": "山上的十块石头",
    "That is a big pile": "那是一大堆",
    "The Fountain of Youth": "青春之泉",
    "The Mystic Anvil": "神秘的砧板",
    "The Solution is MOARE tiles": "解决方案是更多的地块",
    "The solution to all end-game problems": "解决所有终局问题的办法",
    "This is Wood Country": "这里是木之国度",
    "Unlock Alchemy": "解锁炼金术",
    "Upgrades are awesome": "升级太棒了",
    "Upgrades are really awesome": "升级真的很棒",
    "Vertical Limit": "垂直极限",
    "Volcanic Storage": "火山存储",
    "We can't stay here": "我们不能待在这里",
    "We have Fishies": "我们有鱼儿",
    "Wisdom Grid Unlock": "智慧网格解锁",
    "With the Power of Science": "借助科学的力量",
    "World Tree Branch": "世界之树分支",
    "World Tree Djungle": "世界之树丛林",
    "World Tree Roots": "世界之树根系",
    "World Tree Sapling": "世界之树幼苗",
    "World Tree Trunk": "世界之树树干",
    "Yes, we are ready!": "是的，我们准备好了！",
    "You are probably prestiging too much": "你可能过于自命不凡了",
    "You know, I'm rich": "你知道吗，我很富有",
    "Blacksmithing Storage": "铁匠铺存储",
    "Hardened Pickaxes": "硬化镐",
    "Increases Coal storage by 150, Iron Ore storage by 150, and Iron Ingots storage by 450": "使煤炭存储量增加 150，铁矿石存储量增加 150，铁锭存储量增加 450",
    "Increases Iron Ingots storage by 50 per Empty Land owned": "拥有的每块空地，都使铁锭存储量增加 50",
    "Iron Ingot Warehousing": "铁锭仓库",
    "Save often to avoid losing progress!": "经常保存以避免丢失进度！",
    "Wood Storage Scaling": "木材仓库扩容",
    "Forging...": "锻造中...",
    "Inputs Required:": "输入要求:",
    "Outputs:": "输出:",
    "Iron Ingots": "铁锭",
    "more": "更多",
    "Iron Ingots": "铁锭",
    "Reset Now": "立即重置",
    "Show Wisdom Grid": "显示智慧网格",
    "Extra Wisdom Points in 5 tiles": "额外的智慧点在5块地块",
    "Stone Storage Scaling": "石头存储扩展",
    "The grid extends in all directions - keep exploring!": "网格向各个方向延伸——继续探索吧！",
    "Wisdom Points gained is based on the amount of Tiles owned in the current run": "本轮游戏所拥有的方块数量决定了获得的智慧点",
    "Wisdom Points on Reset": "重置可获得智慧点",
    "Cave Spelunking": "洞穴探险",
    "Digging in Shifts": "轮班挖掘",
    "Forest tile cost is 20% cheaper": "森林地块成本便宜20%",
    "Gain 10 Iron Ore every 18 seconds": "每 18 秒获得 10 个铁矿石",
    "Gain 8 Stone every 7 seconds and 9 Iron Ore every 7 seconds": "每7秒获得8石头，每7秒获得9铁矿石",
    "Increases Coal storage by 175, Iron Ore storage by 175, and Iron Ingots storage by 550": "煤炭储存量增加 175，铁矿石储存量增加 175，铁锭储存量增加 550",
    "Increases Iron Ingots storage by 500 per Forge owned": "每个锻炉增加500个铁锭储存",
    "Industrial Juggernaut": "工业巨兽",
    "Lid of a Cola Bottle": "可乐瓶盖",
    "Mechanized Forestry": "林业机械化",
    "Quarry tile cost is 20% cheaper": "采石场地块成本降低了20%",
    "Ranger Patrols": "护林员巡逻",
    "Sell off worthless Relics": "出售无用的遗迹",
    "Steam-powered Mining Machinery": "蒸汽动力采矿机械",
    "Strip Mining": "露天采矿",
    "Optimized Transport Routes": "优化运输路线",
    "Coal Compacting": "煤炭压缩",
    "Gain 10 Wood every 3 seconds, 10 Stone every 3 seconds, and 10 Coal every 3 seconds": "每3秒获得10木材，每3秒获得10石头，每3秒获得10煤炭",
    "Increases Coal storage by 1,000": "煤炭储存量增加 1000",
    "Universal Income": "全民收入",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "var:": "变量:",
    "AP": "成就点数",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "???": "???",
    "•": "•",
    "−": "−",
    "⊞": "⊞",
    "⊡": "⊡",
    "🔒": "🔒",
    "→": "→",
    "": "",
    "": "",
    "": "",
    "": "",
    "@": "@",
    "^": "^",
    "&": "&",
    "%": "%",
    "--": "--",
    "=": "=",
    "?": "?",
    "!": "!",
    "$": "$",
    "#": "#",
    "/": "/",
    "]": "]",
    "[": "[",
    "+": "+",
    ".": ".",
    "…": "…",
    ":": ":",
    "-": "-",
    "|": "|",
    "(": "(",
    ")": ")",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Gityx游戏': 'Gityx游戏',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    'a': 'a',
    'b': 'b',
    'c': 'c',
    'd': 'd',
    'e': 'e',
    'f': 'f',
    'g': 'g',
    'h': 'h',
    'i': 'i',
    'j': 'j',
    'k': 'k',
    'l': 'l',
    'm': 'm',
    'n': 'n',
    'o': 'o',
    'p': 'p',
    'q': 'q',
    'r': 'r',
    's': 's',
    't': 't',
    'u': 'u',
    'v': 'v',
    'w': 'w',
    'x': 'x',
    'y': 'y',
    'z': 'z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Animations: ": "动画: ",
    "Current Endgame: ": "当前终局: ",
    "Space Background: ": "太空背景: ",
    "Tile Cost: ": "方块成本: ",
    "Your current Tile Cost Multiplier is ": "你当前的方块成本乘数是 ",
    "Only available on: ": "仅可用于: ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    " (Stone)": " (石头)",
    " (Wood)": " (木头)",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)$/,
    /^×([\d\.]+)$/,
    /^x([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^\(([\d\.]+), ([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^\+([\d\.]+)\%$/,
    /^\-([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^\(([\d\.]+),([\d\.]+)\)$/,
    /^\(\-([\d\.]+),([\d\.]+)\)$/,
    /^\(\-([\d\.]+),\-([\d\.]+)\)$/,
    /^\(([\d\.]+),\-([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+) ([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.]+)\/([\d\.]+) ([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^\[([\d\.]+):([\d\.]+):([\d\.]+)\]$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^×([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^Spend (.+) total Globes on World Tree nodes.$/, '在“世界树”节点上总共花费 $1 球。'],
    [/^Converts (.+) Coal \+ (.+) Iron Ore → (.+) Iron Ingots\/sec$/, '转化 $1 煤 + $2 铁矿石 → $3 铁锭/秒'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
    [/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^([\d\.]+)\/s$/, '$1\/秒'],
    [/^\(\+([\d\.]+)\/s\)$/, '(+$1\/秒)'],
    [/^([\d\.,]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^\+([\d\.]+) elves$/, '+$1 精灵'],
    [/^\+([\d\.]+)\% elves$/, '+$1% 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)h ([\d\.]+)m$/, '$1小时 $2分'],
    [/^([\d\.]+)m ([\d\.]+)s$/, '$1分钟 $2秒'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^\+([\d\.,]+) elves$/, '+$1 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) Degrees Celsius$/, '$1 摄氏度'],
    [/^Unlocks after owning ([\d\.,]+) more tiles$/, '再拥有 $1 方块之后解锁'],
    [/^Unlocks after owning ([\d\.,]+) more tile$/, '再拥有 $1 方块之后解锁'],
    [/^Produces ([\d\.,]+) Coal\/sec$/, '生产 $1 煤/秒'],
    [/^Produces ([\d\.,]+) Iron Ore\/sec$/, '生产 $1 铁矿石/秒'],
    [/^Produces ([\d\.,]+) Wood\/sec$/, '生产 $1 木头/秒'],
    [/^Produces ([\d\.,]+) Stone\/sec$/, '生产 $1 石头/秒'],
    [/^Upgrades \(([\d\.,]+)\)$/, '升级 ($1)'],
    [/^Have ([\d\.,]+) Artifacts on hand.$/, '手中持有 $1 神器.'],
    [/^Have ([\d\.,]+) Iron Ingots on hand.$/, '手中持有 $1 铁锭.'],
    [/^Have ([\d\.,]+) Stone on hand.$/, '手中持有 $1 石头.'],
    [/^Have ([\d\.,]+) Wood on hand.$/, '手中持有 $1 木头.'],
    [/^Have ([\d\.,]+) Red Crystals on hand$/, '手中持有 $1 红水晶'],
    [/^Have ([\d\.,]+) Stone on hand on Crystal Peak$/, '手中持有 $1 石头 在水晶山'],
    [/^Have ([\d\.,]+) Wood on hand at once$/, '手中一次性持有 $1 木头.'],
    [/^Have ([\d\.,]+) Stone on hand at once$/, '手中一次性持有 $1 石头.'],
    [/^Have ([\d\.,]+) Coal on hand.$/, '手中持有 $1 煤.'],
    [/^Have ([\d\.,]+) Obsidian storage capacity$/, '拥有 $1 黑曜石 存储容量'],
    [/^Have ([\d\.,]+) Iron Ingot storage capacity on Crystal Peak$/, '拥有 $1 铁锭 存储容量 在水晶山'],
    [/^Have a Coal storage capacity of ([\d\.,]+)$/, '拥有 $1 煤 存储容量'],
    [/^Have a Stone storage capacity of ([\d\.,]+)$/, '拥有 $1 石头 存储容量'],
    [/^Have a Wood storage capacity of ([\d\.,]+)$/, '拥有 $1 木头 存储容量'],
    [/^Have an Iron Ingot storage capacity of ([\d\.,]+)$/, '拥有 $1 铁锭 存储容量'],
    [/^Have an Iron Ore storage capacity of ([\d\.,]+)$/, '拥有 $1 铁矿石 存储容量'],
    [/^Purchase ([\d\.,]+) Dark Forest Upgrades.$/, '购买 $1 黑暗森林升级。'],
    [/^Purchase ([\d\.,]+) Upgrades in a single run.$/, '在单轮游戏中购买 $1 升级。'],
    [/^Purchase ([\d\.,]+) upgrades in a single run$/, '在单轮游戏中购买 $1 升级'],
    [/^Purchase ([\d\.,]+) upgrades total across all runs$/, '在所有游戏轮次中总计购买 $1 升级'],
    [/^Own ([\d\.,]+) Quarries$/, '拥有 $1 采石场'],
    [/^Own ([\d\.,]+) Empty Lands$/, '拥有 $1 空地'],
    [/^Own ([\d\.,]+) Coal Deposits$/, '拥有 $1 煤矿床'],
    [/^Own ([\d\.,]+) Forges$/, '拥有 $1 锻炉'],
    [/^Own ([\d\.,]+) Forests$/, '拥有 $1 森林'],
    [/^Own ([\d\.,]+) Dark Forests.$/, '拥有 $1 黑暗森林.'],
    [/^Own ([\d\.,]+) Empty Land on Dark Forests.$/, '在黑暗森林拥有 $1 空地.'],
    [/^Own ([\d\.,]+) Iron Mines$/, '拥有 $1 铁矿'],
    [/^Own ([\d\.,]+) tiles$/, '拥有 $1 方块'],
    [/^Own ([\d\.,]+) tiles.$/, '拥有 $1 方块.'],
    [/^Own ([\d\.,]+) Rivers on Riverside.$/, '在河畔拥有 $1 河流.'],
    [/^Own ([\d\.,]+) Riverbanks on Riverside$/, '在河畔拥有 $1 河堤'],
    [/^Own ([\d\.,]+) tiles on Meadows.$/, '在草地拥有 $1 方块.'],
    [/^Own ([\d\.,]+) tiles on Crystal Peak.$/, '在水晶山拥有 $1 方块.'],
    [/^Own ([\d\.,]+) Dig Sites.$/, '拥有 $1 挖掘点.'],
    [/^Own ([\d\.,]+) tiles total.$/, '总计拥有 $1 方块.'],
    [/^Own ([\d\.,]+) Mountains.$/, '拥有 $1 高山.'],
    [/^Own ([\d\.,]+) Empty Lands$/, '拥有 $1 空地'],
    [/^Own ([\d\.,]+) tiles total$/, '总计拥有 $1 方块'],
    [/^Gain ([\d\.,]+) Wood every ([\d\.,]+) seconds$/, '每 $2 秒获得 $1 木头'],
    [/^Gain ([\d\.,]+) Coal every ([\d\.,]+) seconds$/, '每 $2 秒获得 $1 煤'],
    [/^Gain ([\d\.,]+) Stone every ([\d\.,]+) seconds$/, '每 $2 秒获得 $1 石头'],
    [/^Gain ([\d\.,]+) Wood every ([\d\.,]+) seconds$/, '每 $2 秒获得 $1 木头'],
    [/^Gain ([\d\.,]+) Coal every ([\d\.,]+) seconds and increases Wood storage by ([\d\.,]+) and increases Coal storage by ([\d\.,]+)$/, '每 $2 秒获得 $1 煤，并且使木头储存量增加 $3，同时使煤炭储存量也增加 $4。'],
    [/^Increases Wood storage by ([\d\.,]+)$/, '提高木头存储量 $1'],
    [/^Increases Wood storage by ([\d\.,]+) and Stone storage by ([\d\.,]+)$/, '提高木头存储量 $1 以及 石头存储量 $2'],
    [/^Increases Wood storage by ([\d\.,]+) per Empty Land owned$/, '拥有的每块空地，都提高木头存储量 $1'],
    [/^Increases Stone storage by ([\d\.,]+)$/, '提高石头存储量 $1'],
    [/^Increases Stone storage by ([\d\.,]+), Coal storage by ([\d\.,]+), and Iron Ore storage by ([\d\.,]+)$/, '提高石头存储量 $1, 煤存储量 $2, 以及铁矿石存储量 $3'],
    [/^Row ([\d\.,]+)$/, '第 $1 行'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^([\d\.,]+) of ([\d\.,]+) Achievements earned$/, '$1 \/ $2 成就已获得'],
    [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);